### ISSUE TITLE
munge in buildroot.

### ISSUE THREAD

**Issue by InspireSemi** [dun/munge#102]
How can I tell ./configure where the libopenssl libs are in a buildroot environment. 

I tried passing LDFLAGS=<path to libopenssl> but ./configure still cannot find openssl.

Do I need to modify the  m4/x_ac_path_openssl.m4  file to point to the libs location in the buildroot tree?
Or is there a env var i can set for this?  

FYI: Just checking for an installed version of openssl limits you.  (IMO)

**Comment by InspireSemi** [comment]
figured this out you need to set the --with-openssl-prefix=<path to openssl in buildroot>

**Comment by dun** [comment]
Glad you figured it out.
