### ISSUE TITLE
cross compiling munge..

### ISSUE THREAD

**Issue by InspireSemi** [dun/munge#103]
Is there anyway to cross compile munge? 

It seems ./configure checks for $cross_compiling and then errors out?

**Comment by dun** [comment]
I've never tried cross-compiling it.  I'll try to look into it sometime this week.

**Comment by InspireSemi** [comment]
It took some digging but you need to set the CONFIG_SITE=file and put in it the var that ./configure is looking for in the tests.  Basically you are seeding the cache to bypass the tests.. 

For munge this is:
ac_cv_file__dev_spx=yes
x_ac_cv_check_fifo_recvfd=yes

Got it cross compiled and into buildroot
Now getting error:
munge: Error: Failed to access "/run/munge/munge.socket.2": No such file or directory

This is a system thing on the embedded system.  Need to dig into your docs some more..

**Comment by InspireSemi** [comment]
Figured out what needed to be added to the rootfs..  some dir need to be created under /var/log and under /run but after that was able to start munged and munge --string=deadbeef
# munge --string=deadbeef
MUNGE:AwQFAAD2tTr/oTENO57Qo0BnR8WLEmHvzKVP9+SATE+ZFifWEULmfRLIkdUM6TGQBtYEnl/0rtL7pv5BdulbEb7rkElhvNRh+xML/tDC9Es7qZjtRpbiAC/F1FHMk/EZEDAWaAOwBZ4VrKbNw1HLP7D3yBKI:

**Comment by dun** [comment]
That error typically means `munged` isn't running; or if it is, it's bound to a different socket than the client is expecting.

Looks like you got it working!

**Comment by InspireSemi** [comment]
Yes still need to add some items to build root to create the dir and then figure out how to autostart munged..

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by dun** [comment]
What arch are you cross-compiling for?

None of my current test systems use `AUTH_METHOD_RECVFD_MKFIFO` or `AUTH_METHOD_RECVFD_MKNOD`, so I'm curious if everything still works for those methods.

**Comment by InspireSemi** [comment]
riscv
