### ISSUE TITLE
OpenSSL 3.0 support

### ISSUE THREAD

**Issue by dun** [dun/munge#110]
OpenSSL 3.0 deprecates all low-level APIs.

- https://wiki.openssl.org/index.php/OpenSSL_3.0#Low_Level_APIs
- https://www.openssl.org/docs/man3.0/man7/migration_guide.html
- https://www.openssl.org/docs/man3.0/man3/EVP_MAC.html
- https://www.openssl.org/docs/man3.0/man7/crypto.html#ALGORITHM-FETCHING
- https://lwn.net/Articles/868536/
- https://fedoraproject.org/wiki/Changes/OpenSSL3.0
- https://packages.debian.org/experimental/openssl
- https://bugzilla.redhat.com/show_bug.cgi?id=2021962

On Debian bookworm/sid with libssl3 3.0.0~~beta2-1:
```
src/common/mac.c:301:5: error: 'HMAC_CTX_new' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
src/common/mac.c:322:5: error: 'HMAC_Init_ex' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
src/common/mac.c:351:5: error: 'HMAC_Update' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
src/common/mac.c:378:5: error: 'HMAC_Final' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
src/common/mac.c:395:5: error: 'HMAC_CTX_free' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
```

**Comment by opoplawski** [comment]
FWIW - Fedora rawhide now has openssl 3.0.  munge FTBFS bug https://bugzilla.redhat.com/show_bug.cgi?id=2021962

**Comment by dun** [comment]
@opoplawski Yep, saw that. I've added it to the links above. Working on it now. Thanks for the notice, tho.

**Comment by kloczek** [comment]
Is it possible to merge those changes and make the new release?

**Comment by dun** [comment]
@kloczek: I got pulled away on another tangent and hadn't gotten back to this. My bad.

I was hoping I could get a quick release out by setting [`OPENSSL_API_COMPAT=0x10100000L`](https://www.openssl.org/docs/manmaster/man7/OPENSSL_API_COMPAT.html). It compiles, but it fails the test suite because Blowfish, CAST5, and RIPEMD160 have been moved to the [legacy provider](https://www.openssl.org/docs/man3.0/man7/migration_guide.html#Legacy-Algorithms). Use of Blowfish and CAST5 at least return an error, but RIPEMD160 causes `munged` to segfault. That rules out the quick fix.

I can drop the other fixes I was hoping to have done, and cut a release once this issue is fixed. But I don't have something ready to merge at the moment.

If you can't wait, you can switch to using Libgcrypt via `./configure --with-crypto-lib=libgcrypt`.
