### ISSUE TITLE
Creating the configure script has errors

### ISSUE THREAD

**Issue by jwattyow** [dun/munge#112]
I'm currently running CentOS 8 on a Parallels VM (running on a Mac Pro). The VM has 6 cores and 32GB of RAM assigned to it.

I downloaded the source for version 0.5.14 and tried to create the configure script using both automake and autoconf. Autoconf created the configure script but configure won't run because install.sh, install-sh or shtools is missing. Shouldn't at least one be included in the distribution?

The errors running automake involve things like:
/usr/share/automake-1.16/am/check2.am: error: am__EXEEXT does not appear in AM_CONDITIONAL
There are also loads of warnings.

I've had such a rough time getting anything with munge to actually work, so excuse the frustration. And then there's slurm but that's another story.

Any help getting this compiled (and running) would be really appreciated.
James.

**Comment by dun** [comment]
Which source did you download? `munge-0.5.14.tar.xz` is the official release tarball which includes a configure script. `munge-0.5.14.zip` is an annoying automatically-generated GitHub asset built directly from git; as such, it does not include the configure script since that is not under version control.

If you have the appropriate dependencies installed, you should be able to create a configure script by running `./bootstrap` -- see #95. (Hmmm... it looks like I need to document that in the installation guide.)

Running `autoreconf` with `--install` will install missing standard auxiliary files like `install-sh`.

Sorry for your frustration. Let me know if you're still having problems and we'll get this sorted out.

**Comment by jwattyow** [comment]
I have downloaded a few distributions - gunzip version, xz version, created the RPM using the instructions provided (some were not successful).

./bootstrap seemed to work ok, but autoreconf --install didn't create the install.sh script. I'm guessing I'm missing some things. Do you have something that describes how to use the *.xz version of the src? Or maybe an RPM (or similar that will work on CentOS 8)?

Thanks for the help!
James.

**Comment by dun** [comment]
Building from the official release tarball is documented in the [Installation Guide](https://github.com/dun/munge/wiki/Installation-Guide).

MUNGE RPMs are in CentOS 8. Looks like it's in their appstream repo. You should be able to `sudo dnf install munge`.
```
$ cat /etc/redhat-release 
CentOS Linux release 8.5.2111

$ dnf info munge
Available Packages
Name         : munge
Version      : 0.5.13
Release      : 2.el8
Architecture : x86_64
Size         : 122 k
Source       : munge-0.5.13-2.el8.src.rpm
Repository   : appstream
Summary      : Enables uid & gid authentication across a host cluster
URL          : https://dun.github.io/munge/
License      : GPLv3+ and LGPLv3+
Description  : MUNGE (MUNGE Uid 'N' Gid Emporium) is an authentication service
             : for creating and validating credentials. It is designed to be
             : highly scalable for use in an HPC cluster environment.
             : It allows a process to authenticate the UID and GID of another
             : local or remote process within a group of hosts having common
             : users and groups. These hosts form a security realm that is
             : defined by a shared cryptographic key. Clients within this
             : security realm can create and validate credentials without the
             : use of root privileges, reserved ports, or platform-specific
             : methods.
```

**Comment by jwattyow** [comment]
I had to reboot my VM but the command 'sudo systemctl status --full munge' is now working (reporting 'active')!

So I think it's working now. Now to get it to work with slurm :-).

Thanks very much for the help!

James.

**Comment by dun** [comment]
You're welcome.
