### ISSUE TITLE
munged: Info: Unauthorized credential for client UID=0 GID=0 inside docker container

### ISSUE THREAD

**Issue by avatar-lavventura** [dun/munge#120]
I am get following ```munged: Info: Unauthorized credential for client UID=0 GID=0``` info message, but `munge` works fine inside a docker container.

I have following configurations in `Dockerfile`, [create-munge-key ](https://github.com/chrisacbr/munge-rpm/blob/el6/create-munge-key) script file.

```bash
RUN /sbin/create-munge-key \
 && chown munge:munge -R /run/munge
```

and having following in my `docker-entrypoint.sh` file which runs when the container starts.

```bash
sudo chown munge:munge -R /run/munge  
nohup sudo -u munge munged -F > /var/log/munged.log &!
```

------

Inside the container:

```bash
$ munge -n | unmunge
STATUS:          Success (0)
ENCODE_HOST:     slurmctl (172.20.0.2)
ENCODE_TIME:     2022-06-27 21:15:19 +0000 (1656364519)
DECODE_TIME:     2022-06-27 21:15:19 +0000 (1656364519)
TTL:             300
CIPHER:          aes128 (4)
MAC:             sha256 (5)
ZIP:             none (0)
UID:             root (0)
GID:             root (0)
LENGTH:          0

$ cat /var/log/munged.log
munged: Notice: Starting munge-0.5.14 daemon (pid 14)
munged: Info: Set origin address to 172.20.0.2 (eth0)
munged: Info: Seeded PRNG with 128 bytes from getrandom()
munged: Info: Enabled PRNG entropy pool enhanced stirring
munged: Info: Updating supplementary group mapping every 3600 seconds
munged: Info: Enabled supplementary group mtime check of "/etc/group"
munged: Info: Removed existing socket "/run/munge/munge.socket.2"
munged: Info: Found 1 user with supplementary groups in 0.000 seconds
munged: Info: Created socket "/run/munge/munge.socket.2"
munged: Info: Created 2 work threads
munged: Info: Unauthorized credential for client UID=0 GID=0
munged: Info: Unauthorized credential for client UID=0 GID=0
munged: Info: Unauthorized credential for client UID=0 GID=0
```

I couldn't figure out where should I use `-u, --restrict-uid` and `-g, --restrict-gid` flags. How could I fix this warning message, is it related to the way `create-munge-key` script runs?

**Comment by dun** [comment]
`create-munge-key` was added by downstream, but it just creates a key using the old recommended way of key generation. It doesn't encode/decode any credentials or have anything to do with this message. By the way, [mungekey](../wiki/Man-8-mungekey) was added in 0.5.14.

The "Unauthorized credential" message is only generated during credential decode (e.g., by `unmunge`), and only generated once per failure. When this happens, the credential is not decoded and an error is returned to the client instead.

If I create a credential with a uid restriction for root and try to decode it, I get an error:
```
$ id
uid=7607(dun) gid=7607(dun) groups=7607(dun),10(wheel) 
$ munge -n -u0 >/tmp/cred
$ unmunge </tmp/cred
unmunge: Error: Unauthorized credential for client UID=7607 GID=7607

$ sudo tail -1 /var/log/munge/munged.log
2022-06-27 15:54:27 -0700 Info:      Unauthorized credential for client UID=7607 GID=7607`
```

But I can decode that credential as root, and the uid restriction will appear in the metadata:
```
$ sudo unmunge </tmp/cred
STATUS:          Success (0)
ENCODE_HOST:     centos08 (192.168.1.65)
ENCODE_TIME:     2022-06-27 15:56:38 -0700 (1656370598)
DECODE_TIME:     2022-06-27 15:56:38 -0700 (1656370598)
TTL:             300
CIPHER:          aes128 (4)
MAC:             sha256 (5)
ZIP:             none (0)
UID:             dun (7607)
GID:             dun (7607)
UID_RESTRICTION: root (0)
LENGTH:          0
```

Your `munged.log` output shows root failed to decode 3 credentials encoded with a uid restriction. Your `munge` command didn't specify a uid/gid restriction, and your `unmunge` output doesn't show one either, nor does it show a decode failure. It appears something else generated those credentials and caused those decode failures. You can verify this by doing a `tail -f /var/log/munged.log` and then doing `munge -n | unmunge`.

**Comment by avatar-lavventura** [comment]
Inside docker id returns:

```
$ id
uid=0(root) gid=0(root) groups=0(root)
```
-------

I was trying to apply from following create-munge-key usage: https://github.com/giovtorres/docker-centos7-slurm/blob/4f1bef5757f5284a55573a23af0185fd7e0c9b51/Dockerfile#L139 , to use Slurm inside docker that also depends on `munge`. I believe default user is `root` in docker that's why its end up with `UID=0 GID=0`.

> It appears something else generated those credentials and caused those decode failures. 

I believe those are slurm binaries run with sudo: `sudo slurmctld`, `sudo slurmd`, `sudo slurmdbd`

When I do `munge -n -u0 >/tmp/cred` and run `sudo slurmctld -Dvv` now I get: `munged: Info: Unauthorized credential for client UID=999 GID=999` warning message

**Comment by dun** [comment]
I don't know what to make of that dockerfile. I don't see it starting `munged` anywhere.

It looks like slurm is the source of the "unauthorized credential" messages. I don't see any issues with munge here.

**Comment by avatar-lavventura** [comment]
The way I start `munged` in the container is:  ```nohup sudo -u munge munged -F > /var/log/munged.log &!``` , I was doing in manually by hand. I can share my own Dockerfile file that uses munged with slurm, for debug but I don't want to take more of your time.

You are right seems like latest slurm version (`22-05-2-1`) may causes this issue. I can try to get contact with slurm developers.

**Comment by dun** [comment]
Your error message `Unauthorized credential for client UID=0 GID=0` shows the client process decoding the credential is running as *root* ("client UID=0 GID=0"). Since this error occurred, the credential must have been encoded with a UID or GID restriction for some user other than *root*.

I think Slurm uses a UID restriction for credentials sent to `slurmd` processes which typically run as *root*, and that UID is restricted to the configured "*SlurmdUser*". I'm wondering if `slurmctld` which, I believe, encoded the credential is instead configured to use a "*SlurmdUser*" other than *root*.

I don't know if that helps any, but it's the only suggestion I have at the moment. Good luck.

**Comment by avatar-lavventura** [comment]
I get lost but I keep trying different combinations to figure out the error :-) 

Hm in my `slurm.conf` and `slurmdbd.conf` file I have `SlurmUser=slurm`. I have `#SlurmdUser=root` in those file but the `SlurmdUser` variable is already `root`  I believe.

```bash
root@slurmctl:# id munge
uid=103(munge) gid=104(munge) groups=104(munge)
root@slurmctl:# id slurm
uid=999(slurm) gid=999(slurm) groups=999(slurm)
```

Ok when I submit a slurm job using like `sbatch slurm_job.sh` the ` Unauthorized credential for client UID=0 GID=0` writting into munged.log. But good thing is everything works fine even this warning message shows up.
