### ISSUE TITLE
slurm: credential data mismatch error, munge 0.5.13 and 0.5.14 interoperability question

### ISSUE THREAD

**Issue by srinivamd** [dun/munge#126]
I have slurmcontroller node running Ubuntu 22 and munge 0.5.14 version (slurm 21) and worker node running CentOS8 with munge 0.5.13 (slurm 20).
 The slurm controller shows the worker node.
When trying to execute an 'srun' command on the centos8 worker node, it fails with `srun: error: Application launch failed: Invalid job credential` 
Checking the CentOS 8 slurmd.log shows:
```
[2022-09-10T17:40:58.753] debug:  Checking credential with 528 bytes of sig data
[2022-09-10T17:40:58.753] error: Credential signature check: Credential data mismatch
[2022-09-10T17:40:58.753] error: Invalid job credential from 20004@10.194.30.22: Invalid job credential
```
Do I need to update munge on worker node to 0.5.14 to match the version on the slurm controller node running Ubuntu 22 to overcome the above error? Or is this a slurm version interoperability issue between ver 21 on controller and version 20 on worker node?

**Comment by dun** [comment]
Both 0.5.13 and 0.5.14 (and 0.5.15) are backwards compatible to at least 0.5.5. So I'm guessing you're having a Slurm compatibility issue between versions 20 and 21.

**Comment by srinivamd** [comment]
Thank you. I've written to `slurm-users@schedmd.com` as well. Awaiting their response.

**Comment by srinivamd** [comment]
Upgrading slurm to slurm 21 fixed the issue. So it was slurm version incompatibility between 20 and 21 that caused it.
Thank you for your help!
