### ISSUE TITLE
RHEL 9

### ISSUE THREAD

**Issue by JuergenUniVie** [dun/munge#128]
Can't install on RHEL9 (Kernel: 5.14.0-70.30.1.el9_0.x86_64)

issue:

[root@dsm x86_64]# rpm --install munge-0.5.15-1.el9.x86_64.rpm
error: Failed dependencies:
        libmunge.so.2()(64bit) is needed by munge-0.5.15-1.el9.x86_64
        munge-libs(x86-64) = 0.5.15-1.el9 is needed by munge-0.5.15-1.el9.x86_64
[root@dsm x86_64]# rpm --install munge-libs-0.5.15-1.el9.x86_64.rpm
error: Failed dependencies:
        munge = 0.5.15-1.el9 is needed by munge-libs-0.5.15-1.el9.x86_64

any idea?

thanks and best wishes,
Juergen

**Comment by dun** [comment]
You need to specify both packages to `rpm` at the same time so it can satisfy the dependencies:
```
# rpm --install munge-0.5.15-1.el9.x86_64.rpm munge-libs-0.5.15-1.el9.x86_64.rpm
```
