### ISSUE TITLE
package fails to install on ubuntu 22.04

### ISSUE THREAD

**Issue by benpolman** [dun/munge#133]
de postinstall runs configure for both the /etc/init.d/munge and the systemd munge.service.
The first one fails because /run/munge does not exist.

The problem is caused by the following  block (which I think should not be present
on a system with systemd) or at least should not be executed

# Automatically added by dh_installinit/13.3.4ubuntu2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abor
t-remove" ] ; then
        if [ -x "/etc/init.d/munge" ]; then
                update-rc.d munge defaults >/dev/null
                if [ -n "$2" ]; then
                        _dh_action=restart
                else
                        _dh_action=start
                fi
                invoke-rc.d munge $_dh_action || exit 1
        fi
fi
# End automatically added section

**Comment by dun** [comment]
I don't understand the problem you're having.

On Ubuntu 22.04.2, I'm able to successfully install munge-0.5.14-6 and generate credentials.

Can you provide more information including the commands you're entering and the exact error messages returned?
