### ISSUE TITLE
Failed to start MUNGE authentication service

### ISSUE THREAD

**Issue by Adrilaf** [dun/munge#136]
I am installing munge and cannot get it started on any of our worker nodes. It generates this error when attempting to start munge
"munge.service: Failed at step EXEC spawning /usr/local/sbin/munged: Permission denied"

I followed the install guide to set the correct permissions, however the error still persists. 
Using --force produces the same error.

Thanks by advance,

**Comment by dun** [comment]
This error message is generated by systemd. Based on the message, it appears `/usr/local/sbin/munged` does not have execute permissions set.

What is the output of `ls -l /usr/local/sbin/munged`?

**Comment by Adrilaf** [comment]
Thanks for the quick reply !

My ls -l : `-rwx------ 1 munge munge 567464 Nov 29 02:58 /usr/local/sbin/munged`

**Comment by dun** [comment]
Start troubleshooting by verifying you can run `munged` from the command-line. For example, as the `munge` user, run `/usr/local/sbin/munged --foreground` and see if the daemon reports any errors.

Once that is working, try starting the daemon (`systemctl start munge.service`). If the daemon fails to start, check `systemctl status munge.service` and `journalctl -xeu munge.service` for details. `munged` should be installed with 0755 permissions so I don't know why yours has 0700; however, I don't think that would cause the problem you're having. But you could try setting it to 0755.

Another possibility for "permission denied" is SELinux. Check if SELinux is running (`sestatus`). If it is, you could try temporarily disabling it (`setenforce 0`) and restarting munged.

**Comment by dun** [comment]
The _run_ directory (`/usr/local/var/run/munge`) is created & removed by systemd. If you're running munged from the command-line, you'd need to create that directory beforehand.

But if you're running RHEL, I recommend you install from RPMs. You should be able to install from their repo via: `sudo dnf install munge`.

I think RHEL8 has 0.5.13, but I don't have a RHEL8 system to check at the moment.

Or if you want to install the latest release (0.5.15), build the RPMs by following the directions [here](https://github.com/dun/munge/wiki/Installation-Guide#installing-from-rpms-on-red-hat-compatible-systems).

If you're installing from rpm, remember to remove the version you installed in `/usr/local` -- I'm guessing you did a `make install`, in which case a corresponding `make uninstall` should clean things up.
