### ISSUE TITLE
Failed to check keyfile "/etc/munge/munge.key": No such file or directory

### ISSUE THREAD

**Issue by Katia-jpg** [dun/munge#137]
Hola, no se si alguien me podría ayudar tengo un problema hace poco comencé a trabajar con slurm y al momento de querer ejecutar un programa me arroja un problema con munge el cual es el siguiente
munge :Error : Failed to check keyfile "/etc/munge/munge.key" :No such file or directory

**Comment by dun** [comment]
You need to [create a key](https://github.com/dun/munge/wiki/Installation-Guide#creating-a-key).

> Hi, I don't know if anyone could help me I've had a problem recently I started working with slurm and when I want to run a show throws me a problem with munge which is the following
>  `munge :Error : Failed to check keyfile "/etc/munge/munge.key" :No such file or directory`
