### ISSUE TITLE
Start munge in docker container with user remapping

### ISSUE THREAD

**Issue by AlessioDelConte** [dun/munge#138]
Hello,

I have a problem with running mune with user remapping on docker. In our server we enabled [user remapping for docker](https://docs.docker.com/engine/security/userns-remap/) (basically it adds 3000 to the uid of the filesystem files of the container). 
In my specific case I need to execute the container without the user re-mapping, possible by using the `--userns=host` when starting docker, **but this stills remaps the container file-system**, see the [disable-namespace-remapping-for-a-container, 3rd paragraph](https://docs.docker.com/engine/security/userns-remap/#disable-namespace-remapping-for-a-container).
The issue is that when I want to start the munge deamon using `gosu munge /usr/sbin/munged` it fails, because the filesystem files are being still re-mapped (with the +3000), but at runtime the munge user is  105 in my case, so it cannot write its log in `/var/log/munge` or any other file because of permission issues of having different uid.
Is there any workaround to this? 

Thank you,
Alessio

**Comment by dun** [comment]
I'm not that familiar with docker so I don't have much to offer here.

You might want to try checking the docker forums because this seems like a problem that's likely been solved before.

This article might be of interest:
https://echorand.me/posts/docker-user-namespacing-remap-system-user/
