### ISSUE TITLE
fail to start munge.service

### ISSUE THREAD

**Issue by yue616** [dun/munge#146]
i'am working on rocky-linux-9.4 system, and the munge was installed by dnf command, but the munge.service cannot be started by systemctl start munge.service, here is the infomation output:
systemctl status munge.service
× munge.service - MUNGE authentication service
     Loaded: loaded (/usr/lib/systemd/system/munge.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Tue 2024-09-17 09:50:19 CST; 1min 15s ago
       Docs: man:munged(8)
    Process: 45710 ExecStart=/usr/sbin/munged (code=exited, status=1/FAILURE)
        CPU: 4ms

Sep 17 09:50:19 master systemd[1]: Starting MUNGE authentication service...
Sep 17 09:50:19 master munged[45712]: munged: Error: Logfile is insecure: world-writable permissions without sticky bit set on "/"
Sep 17 09:50:19 master systemd[1]: munge.service: Control process exited, code=exited, status=1/FAILURE
Sep 17 09:50:19 master systemd[1]: munge.service: Failed with result 'exit-code'.
Sep 17 09:50:19 master systemd[1]: Failed to start MUNGE authentication service.

**Comment by dun** [comment]
Here's the line with the error:
```
munged: Error: Logfile is insecure: world-writable permissions without sticky bit set on "/"
```
It seems your root directory is world-writable. What is the output of `ls -ld /`?

You can remove world-write permissions with: `sudo chmod o-w /`
