### ISSUE TITLE
RHEL 8.10/Fedora 40 Rpmbuild fails: error: Failed to read spec file from munge-0.5.16.tar.gz

### ISSUE THREAD

**Issue by Dahlonega** [dun/munge#147]
Dun,
As stated in the title `rpmbuild -tb munge-0.5.16.tar.gz` returns `error: Failed to read spec file from munge-0.5.16.tar.gz`.
I have tried it with -ts  --clean and -ta --clean.
In the event that it was an issue with the device I also tried on a Fedora 40 device. I understand they have not been specifically tested however I'm hoping they're similar enough to not be the issue.

Possibly related: I have tried it with 0.5.13 (This is the version that is in the Rhel 8 Appstream repo) and it fails with a different error.
`rpmbuild -ta --clean munge-0.5.13.tar.gz`
`error: Bad source: /home/dahlonega/munge-0.5.13.tar.xz: No such file or directory`

It is not lost on me that the Bad source error is  specifying .xz as opposed to .gz

Ultimately I am attempting to build from RPM as slurm requires munge-devel, which does not appear to be in the Rhel 8 repo. (Munge and munge-libs are)

Ps: I appreciated the way you responded in kind to my last issue. It was a much needed chuckle!

**Comment by Dahlonega** [comment]
Downloaded the munge-0.5.16.tar.xz instead of the munge-0.5.16.tar.gz and it seems to have worked fine with 
`rpmbuild -tb --clean munge-0.5.16.tar.xz`

Operator error?

**Comment by dun** [comment]
The official release tarballs that I build are constructed in a manner to work with `rpmbuild -t`. These dist tarballs are named munge-${version}.tar.xz. In contrast, the munge-${version}.tar.gz tarballs are automatically generated by GitHub and do not work with `rpmbuild -t`. Yes, it's unfortunately confusing.

The "-t" option directs `rpmbuild` to look inside the tarball for the spec file. And that embedded spec file specifies the name of the (to be created) tarball in the [`Source0`](https://github.com/dun/munge/blob/4799418430e1d4fb79fa18e5f8b7024b82aabbae/munge.spec.in#L23) tag with an ".xz" suffix.

```
Ps: I appreciated the way you responded in kind to my last issue. It was a much needed chuckle!
```
I'm glad I could brighten your day. :smile:
