### ISSUE TITLE
Red hat

### ISSUE THREAD

**Issue by AMALFARES** [dun/munge#148]
what is the reason that make address of bondo does not read and any command related with ip address that not work and service of network disable in application server network manager red hat:6.5

**Comment by dun** [comment]
I do not understand the problem you're having, but it does not appear to be related to this project.

**Comment by AMALFARES** [comment]
Can you help me how can i share quastion related with scada system in
githup

**Comment by dun** [comment]
I don't know which specific project you're trying to find. Try searching on GitHub and filtering by repositories, discussions, or topics. Good luck.

**Comment by AMALFARES** [comment]
The project about scada system and we have problem in the server can you
have any information about this
