### ISSUE TITLE
Are there any user help lists or something to fault find munge problems?

### ISSUE THREAD

**Issue by gzcwnk** [dun/munge#149]

**Comment by dun** [comment]
I'm not sure what it is that you're asking. There are no active mailing lists. You can open a new issue to ask a question (like this one). As for finding faults, there is a test suite that is a work-in-progress. `libmunge` should have 100% coverage, and I try to add tests for new or refactored code.

**Comment by gzcwnk** [comment]
Following the docs I get to the final test and its asking for a password but I thought the munge.key does this?

[root@node1 ~]# munge -n | ssh vuwunicoslurmd1.ods.vuw.ac.nz unmunge
Password: 
Password: 

[root@node1 ~]# 

ie I dont know what the correct output is but this seems wrong.

The primary IP address should be 130.195.87.21   not 86.21 (second nic), not sure if that matters?

**Comment by gzcwnk** [comment]
[root@node1 ~]# munge -n | ssh vuwunicoslurmd1.ods.vuw.ac.nz unmunge
Password: 
^C
[root@node1 ~]# munge -n | unmunge
STATUS:           Success (0)
ENCODE_HOST:      node1.ods.vuw.ac.nz-clusternet (130.195.87.21)
ENCODE_TIME:      2024-12-02 13:04:46 +1300 (1733097886)
DECODE_TIME:      2024-12-02 13:04:46 +1300 (1733097886)
TTL:              300
CIPHER:           aes128 (4)
MAC:              sha256 (5)
ZIP:              none (0)
UID:              root (0)
GID:              root (0)
LENGTH:           0

[root@node1 ~]# munge -n -t 10 | ssh vuwunicoslurmd1.ods.vuw.ac.nz unmunge
Password: 
^C
[root@node1 ~]# ssh vuwunicoslurmd1.ods.vuw.ac.nz munge -n -t 10 | unmunge
Password: 

Password:

**Comment by dun** [comment]
The test `munge -n | ssh somehost unmunge` is to remotely decode (on host "somehost") a locally-encoded credential. It will not help with the ssh connection password -- you will still need to enter a password unless you have some form of passwordless-ssh configured. This test is to check that the local and remote `munged` daemons are running with the same key, compatible versions, synchronized clocks, etc.
