### ISSUE TITLE
specify network interface for obtaining origin IP address

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dun/munge#23]
**What new or enhanced feature are you proposing?**

Support for specifying which network interface munged will use when obtaining the origin IP address to embed within the credential metadata.

**What goal would this enhancement help you achieve?**

This would allow a client to obtain a credential from a multihomed host such that the embedded origin IP address is relevant to the credential recipient.

_Original issue reported on code.google.com by `chris.m.dunlap` on 18 Jul 2013 at 6:44_

**Comment by wpoely86** [comment]
@dun I'm in this situation: a host has multiple IPs and munged takes the wrong one.

I'm not sure if specify in the network interface is a good solution? A single network interface can have multiple IPs assigned (with ipv6 it's even worse). Why not a option that allows you to specify the hostname directly? We can then check if that IP is assigned to an interface of the host? I will try to hack some code together to do this.

**Comment by dun** [comment]
@wpoely86 This approach looks sensible. I'm thinking I might want to abstract away the call to `getifaddrs()` in case I need to add support via `ioctl()` at some point. I'll dig into this after I wrap up some other stuff. Thanks!

**Comment by kfox1111** [comment]
Trying to use this. I have a container running in a kubernetes cluster running munge. With origin, it still is expecting that the ip address is in the instance, while the internal address is not reverse resolvable on the server. I would like to override the ip with something that is resolvable outside without needing the ip to be on an interface internally. Can this be done?

**Comment by kfox1111** [comment]
There is a force flag which lets it start up, but it seems to then pick 0.0.0.0 as the ip address.

**Comment by dun** [comment]
@kfox1111 As currently implemented, this cannot be done.  The origin address must match an address assigned to a local network interface.  Failure to match will result in an error; if that error is overridden via `--force`, the origin will be set to 0.0.0.0.

Part of the rationale for this is the planned support for restricting credential decoding based on the origin IP address (#71).  My thought was that munged should only be able to decode an address-restricted credential to a local network interface.  But I hadn't considered a case like you're describing.  Can you elaborate on how you're using MUNGE?

**Comment by kfox1111** [comment]
@dun Sorry, this fell off my radar.

We have slurm clusters for hpc work, and we have kubernetes clusters for doing long running services. Sometimes services would like to submit slurm jobs to the hpc clusters. sbatch desn't work without a munge token. munged can be employed on the host, but like I mentioned above, some of the internal networks are visible to munge in this case. An alternate setup would be to run the munged in a pod with its own ip address, but pass --listen to use the ip of the host. In the end, slurm will see that ip address anyway from the pod traffic.

**Comment by kfox1111** [comment]
Looks like 0.5.14 may have the option to do this. I'm building rpms/containers now to try this out. There aren't epel rpms yet for this version. Will update you as I get results back.

**Comment by dun** [comment]
@kfox1111 Yes, I updated the `--origin` option to allow any IPv4 address after your earlier comments. I'm hoping to add IPv6 support in the next release. Please let me know if you encounter problems.

**Comment by kfox1111** [comment]
yeah. Looks like its working. Thanks! :)

**Comment by dun** [comment]
Glad I could be of help.
