### ISSUE TITLE
systemd-tmpfiles munge.conf installed but unpackaged on SLES11, breaks rpmbuild

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dun/munge#27]
**What steps will reproduce the problem?**

The `systemd-tmpfiles` `munge.conf` needs to be excluded from older (hello SLES11) rpm builds in the spec file as it causes rpmbuild to fail.
```
aelwell@iTDS:~/compile> rpmbuild -ta ./munge-0.5.11.tar.bz2
```

**What is the expected output? What do you see instead?**
```
Requires(postun): /bin/sh
Requires: libc.so.6()(64bit) libc.so.6(GLIBC_2.2.5)(64bit) 
libc.so.6(GLIBC_2.3.4)(64bit) libc.so.6(GLIBC_2.4)(64bit)
Checking for unpackaged file(s): /usr/lib/rpm/check-files /var/tmp/munge-0.5.11
error: Installed (but unpackaged) file(s) found:
   /usr/lib/tmpfiles.d/munge.conf

RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/lib/tmpfiles.d/munge.conf
```

**What version of the software are you using? On what operating system?**

munge-0.5.11 on SLES11

**Please provide any additional information below.**

Reported by andrew.elwell in [#11](11#issuecomment-102537500).

*Original issue reported on code.google.com by `chris.m.dunlap` on 19 Dec 2013 at 12:18*

**Comment by dun** [comment]
The top-level `munge.spec` will target the latest CentOS / RHEL release.  RPM specfiles for other distros & releases will be placed in the top-level `extra` directory -- please submit a pull request.

This issue now lists SLES11, Amazon Linux, and CentOS.  I don't have access to SLES or Amazon Linux, but the specfile now works on the latest CentOS so I'm closing this.
