### ISSUE TITLE
munged: Error: Logfile is insecure: group-writable permissions set on "/var/log"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dun/munge#31]
**What steps will reproduce the problem?**

Start munged on Ubuntu 14.04 without use of the `--force` command-line option.

**What is the expected output? What do you see instead?**

munged should start with the default options.  Instead, it fails and exits:
```
$ sudo service munge start
 * Starting MUNGE munged [fail]
munged: Error: Logfile is insecure: group-writable permissions set on "/var/log"
```

**What version of the software are you using? On what operating system?**

munge-0.5.11 on Ubuntu 14.04

**Please provide any additional information below.**

Ubuntu 14.04 changes the `/var/log` directory permissions from 0755 root:root to 0775 root:syslog.  munged is warning of the group-writable permissions on `/var/log`.

Running munged with either the `--force` or `--syslog` command-line option will override this warning:

* `--force` will override errors (turning them into warnings) for an existing local domain socket, a lack of entropy for the PRNG, and some potentially insecure file/directory permissions
* `--syslog` will bypass the permission check on `/var/log` since log messages will instead be routed to the syslog service

These command-line options can be specified in the `OPTIONS` variable in `/etc/default/munge`:
```
OPTIONS="--force"
```

https://bugs.launchpad.net/ubuntu/+source/munge/+bug/1287624

*Original issue reported on code.google.com by `chris.m.dunlap` on 29 May 2014 at 8:00*

**Comment by dun** [comment]
Ubuntu 15.04 switched to systemd. It does not use `/etc/init.d/munge` or `/etc/default/munge`. To specify command-line options for munged, perform the following steps:

1. `systemctl edit --system --full munge`

    This command will perform the following actions:

    1. Copy `munge.service` to `/etc/systemd/system/munge.service`
    1. Invoke an editor on this new `munge.service` file
    1. Reload the systemd configuration afterwards

    While in the editor, append either `--syslog` or `--force` to the `ExecStart` line:
    ```
    ExecStart=/usr/sbin/munged --syslog
    ```

    If `munge.service` is instead manually edited, a `systemctl daemon-reload` will be necessary to reload the systemd configuration afterwards.

1. `systemctl enable munge`

    This command will enable the service at boot.

1. `systemctl start munge`

    This command will start the daemon.
