### ISSUE TITLE
Failed to access "/usr/local/var/run/munge/munge.socket.2 No such file or directory (err=6)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dun/munge#38]
Hello. I can't run the basic tests of munge as referred to in InstallationGuide

**What steps will reproduce the problem?**

```
munge -n
```

**What is the expected output? What do you see instead?**

No error should be displayed

Instead:

```
munge: Error: Failed to access "/usr/local/var/run/munge/munge.socket.2": No such file or directory
```

**What version of the software are you using? On what operating system?**

0.5.11. CentOS 6

**Please provide any additional information below.**

```
mycomputer:Munge username$ /etc/init.d/munge status
munged (pid  5937) is running...
```

Installation was done as root but then chown'd to my username.

Any suggestions for further debugging would be appreciated. I expect the defect is with the user rather than the system...

Thank you.

James

_Original issue reported on code.google.com by `jamesresearching` on 25 Nov 2014 at 9:38_

**Comment by unitsmanolis** [comment]
Hi, I have a similar problem.

Window 10 with WSL

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

$ which munge
/usr/bin/munge

$ sudo apt install munge

Reading package lists... Done
Building dependency tree
Reading state information... Done
munge is already the newest version (0.5.13-2build1).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.

$/etc/init.d/munge status
munged (pid 10078) is running

$sudo munge -n
munge: Error: Failed to access "/run/munge/munge.socket.2": No such file or directory

$/usr/sbin/munged -h | grep socket
  -S, --socket=PATH        Specify local socket [/run/munge/munge.socket.2]

$ cd /run/munge/
$ ls 
#The folder is empty!

Many thanks

**Comment by dun** [comment]
@unitsmanolis Please open a new issue if you're having problems. This issue is closed.

**Comment by ChristopherEeles** [comment]
@unitsmanolis,

I had the same issue in WSL2 running Ubuntu 22.04.

I fixed with:
```
sudo service munge start
```

Best,
Chris
