### ISSUE TITLE
munge service doesn't work after fresh RPM install prior to reboot

### ISSUE THREAD

**Issue by magicite** [dun/munge#39]
I built and installed munge for SLES12 using the spec file.  The install went fine, but when I went to start the service (prior to reboot) it failed due to:

> purge-head12:~ # journalctl -xn | tail
> May 27 14:37:46 datawarp-head12 munged[29102]: munged: Error: Failed to check 
> pidfile dir "/var/run/munge": cannot canonicalize "/var/run/munge": No such 
> file or directory

I believe this is a result of not doing the following (from https://en.opensuse.org/openSUSE:Systemd_packaging_guidelines ):

> If you expect this file / directory to be available after package installation 
> (and before reboot), remember to add in your package %post :
> 
> systemd-tmpfiles --create /usr/lib/tmpfiles.d/<file_name>

**Comment by dun** [comment]
The top-level `munge.spec` will target the latest CentOS / RHEL release.  RPM specfiles for other distros & releases will be placed in the top-level `extra` directory -- please submit a pull request.

**Comment by dun** [comment]
Closing out old issue.
