### ISSUE TITLE
rpmbuild errors

### ISSUE THREAD

**Issue by spiro-stathakis** [dun/munge#43]
Hi related to #36 I am experiencing a similar issue : 
On Centos  7.1.1503 I am trying to build an RPM package using the command 

rpmbuild -tb --clean  munge-0.5.11.tar.bz2 
and it fails with the following : 

error: Installed (but unpackaged) file(s) found:
   /usr/lib/systemd/system/munge.service
   /usr/lib/tmpfiles.d/munge.conf

RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/lib/systemd/system/munge.service
   /usr/lib/tmpfiles.d/munge.conf

Is there any update on the 0.5.12 release please? 

Cheers.

**Comment by dun** [comment]
I should have the specfile cleaned up in the next few days. After that, I'll look at what absolutely has to be in the next release and see if I can have something out by the end of the month.

**Comment by dun** [comment]
Duplicate of #33.
