### ISSUE TITLE
Installation options

### ISSUE THREAD

**Issue by outpaddling** [dun/munge#48]
FYI,

You might want to also mention FreeBSD ports and pkgsrc on

https://github.com/dun/munge/wiki/Installation-Guide

On FreeBSD, munge can be installed with

pkg install munge

or

cd /usr/ports/security/munge && make install

On NetBSD:

pkgin install munge

cd /usr/pkgsrc/security/munge && make install

As pkgsrc is cross-platform, the last command can be used on just about any POSIX platform.  I use pkgsrc to deploy munge and hundreds of other packages on CentOS.

Cheers,

    Jason

**Comment by dun** [comment]
I've updated the wiki. Thanks for the info!
