### ISSUE TITLE
Munge installation in Centos 6.9

### ISSUE THREAD

**Issue by mohseniaref** [dun/munge#59]
Hi,

I am using Centos 6.9 and I can't run munge,would you please guide me to solve this problem
[root@localhost munge]#  sudo service munge start --force
Starting MUNGE: mungedmunged: Error: Logfile is insecure: "/var/log/munge/munged.log" should be owned by UID 496
                                                           [FAILED]

**Comment by dun** [comment]
I think the problem you're having is that the init script (`/etc/init.d/munge`) is configured to run the daemon as a non-root user, and the logfile `/var/log/munge/munged.log` is not owned by that user.

You can check this by looking for the `USER` variable in `/etc/init.d/munge` and `/etc/sysconfig/munge`. If you examine `/etc/passwd`, that user should have UID 496. You can then change the logfile ownership via `sudo chown 496 /var/log/munge/munged.log`. The daemon will stop as soon as it encounters an error, so it may fail on a different error once this first one is corrected. But it will tell you the cause of the error so you can take steps to correct it.

The `--force` option can be used to override these warnings, but it needs to be passed to `munged`. You can do this by adding it to the `DAEMON_ARGS` variable in `/etc/sysconfig/munge` (`DAEMON_ARGS="--force"`), and then starting the daemon (`sudo service munge start`).

**Comment by zouhair0** [comment]
Hello,
I try to install munge in our server (CentOS 6).
I correct the permissions with : chown -R munge: /etc/munge/ /var/log/munge/
chmod 0700 /etc/munge/ /var/log/munge/
But, when i tried to launch munge with : "sudo service munge start" or with the command "sudo /etc/init.d/munge start"
I received this message : Starting MUNGE: mungedmunged: Error: Unable to resolve host "clt-hpcurep-s"
[FAILED]
Can anyone help me please to solve this problem !
