### ISSUE TITLE
munge.service failed in Centos7.3

### ISSUE THREAD

**Issue by helloxwm** [dun/munge#60]
Hi,
I am using Centos 7.3 ,but there is something wrong when I attempting to run systemctl start munge
```
[root@localhost munge]# systemctl start munge
Job for munge.service failed because the control process exited with error code. See "systemctl status munge.service" and "journalctl -xe" for details.
[root@localhost munge]# systemctl status munge.service -l
● munge.service - MUNGE authentication service
   Loaded: loaded (/usr/local/lib/systemd/system/munge.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2017-07-31 17:08:52 CST; 21s ago
     Docs: man:munged(8)
  Process: 28056 ExecStart=/usr/local/sbin/munged (code=exited, status=1/FAILURE)

Jul 31 17:08:52 localhost.localdomain systemd[1]: Starting MUNGE authentication service...
Jul 31 17:08:52 localhost.localdomain systemd[1]: munge.service: control process exited, code=exited status=1
Jul 31 17:08:52 localhost.localdomain systemd[1]: Failed to start MUNGE authentication service.
Jul 31 17:08:52 localhost.localdomain systemd[1]: Unit munge.service entered failed state.
Jul 31 17:08:52 localhost.localdomain systemd[1]: munge.service failed.
[root@localhost munge]# journalctl -xe
Jul 31 17:06:23 localhost.localdomain yum[27897]: Installed: munge-devel-0.5.11-3.el7.x86_64
Jul 31 17:06:49 localhost.localdomain firefox.desktop[3626]: (firefox:7914): Gtk-CRITICAL **: gt
Jul 31 17:06:49 localhost.localdomain firefox.desktop[3626]: (firefox:7914): Gtk-CRITICAL **: gt
Jul 31 17:06:49 localhost.localdomain firefox.desktop[3626]: (firefox:7914): Gtk-CRITICAL **: gt
Jul 31 17:07:03 localhost.localdomain firefox.desktop[3626]: (firefox:7914): Gtk-CRITICAL **: gt
Jul 31 17:08:35 localhost.localdomain polkitd[911]: Registered Authentication Agent for unix-pro
Jul 31 17:08:35 localhost.localdomain systemd[1]: Reloading.
Jul 31 17:08:35 localhost.localdomain polkitd[911]: Unregistered Authentication Agent for unix-p
Jul 31 17:08:52 localhost.localdomain polkitd[911]: Registered Authentication Agent for unix-pro
Jul 31 17:08:52 localhost.localdomain systemd[1]: Starting MUNGE authentication service...
-- Subject: Unit munge.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit munge.service has begun starting up.
Jul 31 17:08:52 localhost.localdomain munged[28056]: munged: Error: Failed to check logfile dir 
Jul 31 17:08:52 localhost.localdomain systemd[1]: munge.service: control process exited, code=ex
Jul 31 17:08:52 localhost.localdomain systemd[1]: Failed to start MUNGE authentication service.
-- Subject: Unit munge.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit munge.service has failed.
-- 
-- The result is failed.
Jul 31 17:08:52 localhost.localdomain systemd[1]: Unit munge.service entered failed state.
Jul 31 17:08:52 localhost.localdomain systemd[1]: munge.service failed.
Jul 31 17:08:52 localhost.localdomain polkitd[911]: Unregistered Authentication Agent for unix-p
```
Thank you !

**Comment by rmachad5** [comment]
I am also running centOS 7.3 and when I run rpmbuild -tb --clean munge-x.y.z.tar.bz2, I get a failed to read spec file.

**Comment by dun** [comment]
@helloxwm: The munged error is:
```
Jul 31 17:08:52 localhost.localdomain munged[28056]: munged: Error: Failed to check logfile dir 
```
The output from journalctl above failed to wrap presumably due to the pager; you can disable the pager via `--no-pager`. The part of the munged error message that was truncated contains the name of the directory (probably "/var/log/munge") followed by the reason for the error.

I have a CentOS 7.3.1611 vm running munge-0.5.12-1.el7.centos.x86_64 without problems. Can you retry `journalctl -xe --no-pager` to get the full text of the error message?

**Comment by dun** [comment]
@rmachad5: On CentOS 7.3.1611, I'm able to build a binary rpm from the released 0.5.12 tarball via `rpmbuild -tb --clean munge-0.5.12.tar.xz`. If you're still having trouble, please open a new issue and include the name/location of the tarball in question along with the failed output.

**Comment by helloxwm** [comment]
@dun thanks,here is the error message:
Aug 02 08:31:43 localhost.localdomain systemd[1]: Starting MUNGE authentication service...
-- Subject: Unit munge.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit munge.service has begun starting up.
Aug 02 08:31:43 localhost.localdomain munged[4001]: munged: Error: Failed to check logfile dir "/usr/local/var/log/munge": cannot canonicalize "/usr/local/var/log/munge": No such file or directory
Aug 02 08:31:43 localhost.localdomain systemd[1]: munge.service: control process exited, code=exited status=1
Aug 02 08:31:43 localhost.localdomain systemd[1]: Failed to start MUNGE authentication service.
-- Subject: Unit munge.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit munge.service has failed.
-- 
-- The result is failed.
Aug 02 08:31:43 localhost.localdomain systemd[1]: Unit munge.service entered failed state.
Aug 02 08:31:43 localhost.localdomain systemd[1]: munge.service failed.
Aug 02 08:31:43 localhost.localdomain polkitd[901]: Unregistered Authentication Agent for unix-process:3994:30299 (system bus name :1.96, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.utf8) (disconnected from bus)
Aug 02 08:32:30 localhost.localdomain firefox.desktop[3649]: (firefox:3649): Gtk-CRITICAL **: gtk_icon_theme_lookup_icon_for_scale: assertion 'scale >= 1' failed

**Comment by dun** [comment]
munged is trying to check the logfile directory "/usr/local/var/log/munge". That directory doesn't exist, so munged exits.

It appears that you've built munge from source such that it was configured to use the default prefix of "/usr/local". The version of munge from CentOS (currently, munge-0.5.11-3.el7.x86_64) is compiled to use the logfile directory "/var/log/munge", and that directory is created by the rpm.

There are several ways you could address this:
1. Create this missing directory.
  `sudo mkdir -p /usr/local/var/log/munge; sudo chown munge:munge /usr/local/var/log/munge`
2. Run munged with `--syslog` to redirect log messages to syslog instead of writing them to a logfile.
  See #31 for details on how to specify this command-line option.
3. Install munge from CentOS (currently at v0.5.11).
  `sudo yum install munge`

**Comment by helloxwm** [comment]
@dun  I tried three ways, but all failed.

**Comment by dun** [comment]
Failed with the same error, or a new error?

**Comment by helloxwm** [comment]
munged: Error: Failed to check PRNG seed dir "/usr/local/var/lib/munge": cannot canonicalize "/usr/local/var/lib/munge": No such file or d

**Comment by dun** [comment]
munged is trying to check the directory "/usr/local/var/lib/munge". That directory doesn't exist, so munged exits. You'll also need to create that.

And while you're at it, you should probably create "/usr/local/var/run/munge" since that's what munged will check for next. These directories are normally created during `make install`, and installed with the rpm.

These directories are listed in the [installation guide](https://github.com/dun/munge/wiki/Installation-Guide#securing-the-installation). You'll also need to [create a secret key](https://github.com/dun/munge/wiki/Installation-Guide#creating-a-secret-key).

**Comment by helloxwm** [comment]
I do what the installation guide said, and created a secret key.  T^T
[root@localhost xwm]# systemctl start munge
[root@localhost xwm]# munge -n
munge: Error: Failed to access "/var/run/munge/munge.socket.2": No such file or directory

**Comment by dun** [comment]
The socket is created by the daemon. If the socket isn't there, then the daemon probably isn't running. What is the output of `systemctl status munge`?

**Comment by helloxwm** [comment]
munge.service - MUNGE authentication service
   Loaded: loaded (/etc/systemd/system/munge.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-08-02 13:16:48 CST; 14min ago
     Docs: man:munged(8)
  Process: 10433 ExecStart=/usr/local/sbin/munged --syslog (code=exited, status=0/SUCCESS)
 Main PID: 10435 (munged)
   CGroup: /system.slice/munge.service
           └─10435 /usr/local/sbin/munged --syslog

Aug 02 13:16:48 localhost.localdomain systemd[1]: Started MUNGE authentication service.
Aug 02 13:16:49 localhost.localdomain munged[10435]: Stirring PRNG entropy pool
Aug 02 13:16:52 localhost.localdomain munged[10435]: Stirring PRNG entropy pool
Aug 02 13:16:56 localhost.localdomain munged[10435]: Stirring PRNG entropy pool
Aug 02 13:17:05 localhost.localdomain munged[10435]: Stirring PRNG entropy pool
Aug 02 13:17:22 localhost.localdomain munged[10435]: Stirring PRNG entropy pool
Aug 02 13:17:54 localhost.localdomain munged[10435]: Stirring PRNG entropy pool
Aug 02 13:18:59 localhost.localdomain munged[10435]: Stirring PRNG entropy pool
Aug 02 13:21:07 localhost.localdomain munged[10435]: Stirring PRNG entropy pool
Aug 02 13:25:24 localhost.localdomain munged[10435]: Stirring PRNG entropy pool

**Comment by dun** [comment]
Is there a socket `/usr/local/var/run/munge/munge.socket.2`?

**Comment by dun** [comment]
Also, is there both a `/usr/bin/munge` and a `/usr/local/bin/munge`?

**Comment by helloxwm** [comment]
yes....

**Comment by dun** [comment]
Does `/usr/local/bin/munge -n` work?

**Comment by helloxwm** [comment]
No such file or directory

**Comment by dun** [comment]
So it appears that you have the daemon installed in /usr/local/sbin/munged. That daemon is looking for files under the /usr/local hierarchy. But you have the client installed in /usr/bin/munge, and that client is looking for files in the standard system hierarchy (i.e., not /usr/local). So how did you install munge on this system?

**Comment by dun** [comment]
Does `munge -n -S /usr/local/var/run/munge/munge.socket.2` work?

**Comment by helloxwm** [comment]
I tried two ways, yum and installation guide. So what should I do next?

**Comment by helloxwm** [comment]
here
[root@localhost xwm]# munge -n -S /usr/local/var/run/munge/munge.socket.2
MUNGE:AwQFAAA+fGQ75C8+if6pBK77/54M3qZL9FeRvSr3SSvRiRyrk4e4/5klOpBcNlvLnvxtmW9v02pubaZQcwJCpTJa+o6nBWD5Ngnyh1FOSVgoVp38BAueCyDLQXEBXhptaAVtzUQ=:

**Comment by dun** [comment]
It looks like you have a partial installation of both. I think the easiest thing to do would be to completely remove both, and then re-install via yum.

**Comment by helloxwm** [comment]
Would you please teach me how to remove them?   QAQ

**Comment by dun** [comment]
To remove the installation via yum:
`sudo yum autoremove munge`

How exactly did you install the version under /usr/local?

**Comment by dun** [comment]
Make sure to stop the currently running daemon (`systemctl stop munge`), and verify it is no longer running via `ps auxw | grep munged`.

If you installed via `make install`, there is a corresponding `make uninstall` target you could try. If not, you might need to manually remove the files from /usr/local. The following list should be most of them:
```
/usr/local/bin/munge
/usr/local/bin/remunge
/usr/local/bin/unmunge
/usr/local/etc/rc.d/init.d/munge
/usr/local/etc/sysconfig/munge
/usr/local/include/munge.h
/usr/local/lib/libmunge.a
/usr/local/lib/libmunge.la
/usr/local/lib/libmunge.so
/usr/local/lib/libmunge.so.2
/usr/local/lib/libmunge.so.2.0.0
/usr/local/lib/pkgconfig/munge.pc
/usr/local/lib/systemd/system/munge.service
/usr/local/lib/tmpfiles.d/munge.conf
/usr/local/sbin/munged
/usr/local/share/man/man1/munge.1
/usr/local/share/man/man1/remunge.1
/usr/local/share/man/man1/unmunge.1
/usr/local/share/man/man3/munge.3
/usr/local/share/man/man3/munge_ctx.3
/usr/local/share/man/man3/munge_ctx_copy.3
/usr/local/share/man/man3/munge_ctx_create.3
/usr/local/share/man/man3/munge_ctx_destroy.3
/usr/local/share/man/man3/munge_ctx_get.3
/usr/local/share/man/man3/munge_ctx_set.3
/usr/local/share/man/man3/munge_ctx_strerror.3
/usr/local/share/man/man3/munge_decode.3
/usr/local/share/man/man3/munge_encode.3
/usr/local/share/man/man3/munge_enum.3
/usr/local/share/man/man3/munge_enum_int_to_str.3
/usr/local/share/man/man3/munge_enum_is_valid.3
/usr/local/share/man/man3/munge_enum_str_to_int.3
/usr/local/share/man/man3/munge_strerror.3
/usr/local/share/man/man7/munge.7
/usr/local/share/man/man8/munged.8
```

Once everything is clean, you should be able to install via yum:
`sudo yum install munge`

**Comment by helloxwm** [comment]
I don't remember what I did to my computer.  I followed so many installations.

**Comment by helloxwm** [comment]
thank you so much. I'll do it right now.

**Comment by dun** [comment]
Sorry you've had so much difficulty getting this installed. #37 and #38 describe similar problems where people have gotten the client (munge) and server (munged) executables compiled differently so they don't communicate with one another. If I can figure out how people get things installed in this manner, then I can update the installation guide to warn against it.

Let me know if you're still having problems once you get it re-installed.

**Comment by helloxwm** [comment]
sure, thanks a lot.   : )  👍

**Comment by helloxwm** [comment]
still have problem with munge.log 
[xwm@localhost munge]$ munged
munged: Error: Failed to check logfile "/var/log/munge/munged.log": Permission denied
via sudo ls -l /var/log/munge/munged.log
ls: cannot access /var/log/munge/munged.log: No such file or directory

and then, I checked the /var/log/munge, nothing in the directory.  -.-

**Comment by dun** [comment]
The "/var/log/munge" directory should be owned by the `munge` user. As such, you'll need to run `/usr/sbin/munged` as the `munge` user. This configuration is specified in the `/usr/lib/systemd/system/munge.service` file (via the `User=munge` and `Group=munge` directives). The easiest way to run munged as the correct user is via `systemctl start munge`.

**Comment by helloxwm** [comment]
The "/var/log/munge" directory is owned by munge user, but how can i know if I run munged successfully by via systemctl start munge

**Comment by dun** [comment]
`systemctl status munge` will show whether or not the daemon is running. If it is, you can test it with the client by doing `munge -n` (or `munge -n | unmunge` to see if a credential can be encoded and then successfully decoded).

**Comment by helloxwm** [comment]
[xwm@localhost munge]$ munge -n
MUNGE:AwQDAADvRaOZR7pgbn+EHNj16TeAyNjKZkj67EBhmieVDleQh1CzotNFK3g4QyeeUA1P5/L5PCxFaZQGe4IUan4hcafLjxaj6WLlP648/uaYKlb91h6VXw4=:

Is that all right? I don't understand this.

**Comment by dun** [comment]
It looks like it's working! Congratulations!

`munge` generates an encoded credential containing information such as your UID and GID. `unmunge` takes an encoded credential, decodes it, and returns the metadata and optional payload. So try `munge -n | unmunge`.

**Comment by helloxwm** [comment]
[xwm@localhost munge]$ munge -n | unmunge
STATUS:           Success (0)
ENCODE_HOST:      localhost (127.0.0.1)
ENCODE_TIME:      2017-08-02 15:48:26 +0800 (1501660106)
DECODE_TIME:      2017-08-02 15:48:26 +0800 (1501660106)
TTL:              300
CIPHER:           aes128 (4)
MAC:              sha1 (3)
ZIP:              none (0)
UID:              xwm (1000)
GID:              xwm (1000)
LENGTH:           0

**Comment by dun** [comment]
Looks like everything is working!

**Comment by helloxwm** [comment]
aaaaa, I'm gonna cry. express thanks on my knees!!!

**Comment by dun** [comment]
Perseverance pays off. I'm glad you were finally able to get this working.
