### ISSUE TITLE
Invalid Credential

### ISSUE THREAD

**Issue by allaneng** [dun/munge#62]
I am trying to use munge with Slurm. I have been testing munge with the procedure mentioned in the installation guide. I can run the following command from the local host,
$ munge -n | unmunge
and munge will work correctly. However the problem arises when I try to use,
$ munge -n | ssh <somehost> unmunge
I will get an invalid credential error every time. I have checked the credentials in /etc/munge/munge.key on each server with diff and they are exactly the same. Both machines have the same system time from a ntp server. Any suggestions on how to fix this would be appreciated.

**Comment by dun** [comment]
Most likely, the munge keys on these two hosts differed when the daemons were started. munged only reads the key when the daemon is started. If you've already verified that the keys are the same on both hosts, try restarting munged on both hosts and repeating the test.

**Comment by allaneng** [comment]
Thanks. That was the issue.
