### ISSUE TITLE
munge.key location in /etc/sysconfig/munge - but /etc/init.d/munge still expects it to be in /etc/munge?

### ISSUE THREAD

**Issue by StevenSilk** [dun/munge#65]
Hello,
We use diskless compute nodes with a shared /etc/ directory.  So we have relocated the munge.key. We thought since we put the location into /etc/sysconfig/munge it should work.  Unfortunately the /etc/init.d/munge still expects it to be a real file and to be located in /etc/munge/.  (not a link).  We have several work arounds - but it would be nice if the install from the yum repository would work properly.
thank you!
Steve

**Comment by dun** [comment]
Please provide the following:
1. the name of the linux distro
2. the version of munge
3. the error message text (if possible)

**Comment by StevenSilk** [comment]
CentOS 6.9
munge-0.5.10 (2011-02-25)
Parsed user as munge
/etc/munge/munge.key does not exist, generate with create-munge-key
Sorry to be so slow with the reply - crazy busy at the moment.
