### ISSUE TITLE
want password from me when I try login other server via munge

### ISSUE THREAD

**Issue by ertanerbek** [dun/munge#67]
Hi,

This is my munge setup result on debian

```
root@node1:~# munge -n
MUNGE:AwQDAABhlsSQ2bku9lhrTEWUT7fS5O4G4cjaY1T4AgtAST8eV88wjka/NCqQns8nG42XunmvdmA28TM/LEvSYBsIq3ffnb8W9QaEKG3Pn/fnwF/aJYKZdVY=:

root@node1:~# munge -n | unmunge
STATUS:           Success (0)
ENCODE_HOST:      node1@slurm.lc (127.0.1.1)
ENCODE_TIME:      2019-02-25 15:25:17 +0300 (1551097517)
DECODE_TIME:      2019-02-25 15:25:17 +0300 (1551097517)
TTL:              300
CIPHER:           aes128 (4)
MAC:              sha1 (3)
ZIP:              none (0)
UID:              root (0)
GID:              root (0)
LENGTH:           0

root@node1:~# remunge
2019-02-25 15:25:21 Spawning 1 thread for encoding
2019-02-25 15:25:21 Processing credentials for 1 second
2019-02-25 15:25:22 Processed 5634 credentials in 1.000s (5632 creds/sec)

root@node1:~# munge -n | ssh 192.168.25.62 unmunge
root@192.168.25.62's password:

root@node1:~# munge -n | ssh node2 unmunge
root@node2's password:

root@node1:~# dpkg -l | grep munge
ii  libmunge-dev                  0.5.12-1+b1                    amd64        authentication service for credential -- development package
ii  libmunge2                     0.5.12-1+b1                    amd64        authentication service for credential -- library package
ii  munge                         0.5.12-1+b1                    amd64        authentication service to create and validate credentials

root@node1:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch
```

as your see when I was try login other server via munge server want password from me, where is wrong what I can make now ?

**Comment by dun** [comment]
MUNGE doesn't enable passwordless ssh access. The command `munge -n | ssh node2 unmunge` is simply sending the credential from `munge` stdout on node1 to `unmunge` stdin on node2 via ssh. This is checking whether a credential encoded on node1 can be decoded on node2 -- which should be the case if both nodes have `munged` running and configured to use the same key.

I looks like MUNGE is properly configured and working on node1. If you don't have passwordless ssh configured between node1 and node2, you'll need to enter your password when prompted by ssh. If you don't have ssh configured to allow root logins (which should be the case), you can run the `munge -n | ssh node2 unmunge` command as a non-privileged user. But you'll need to have node2 configured to allow ssh access for you before you can perform this MUNGE check.

**Comment by ertanerbek** [comment]
I was wrong understand munge :) So actually my munge was work...
