### ISSUE TITLE
libmunge.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by conanyangqun** [dun/munge#74]
Hi, guys.
When I run `mungekey --verbose`, it show an error as below.
```bash
error while loading shared libraries: libmunge.so.2: cannot open shared object file: No such file or directory.
```
I compiled munge-0.5.14 on Centos7 using the below command.
```bash
curl -L 'https://github.com/dun/munge/releases/download/munge-0.5.14/munge-0.5.14.tar.xz' -o munge.tar.xz
tar xvf munge.tar.xz

cd munge-0.5.14
./configure --prefix=/usr \
	--prefix=/usr \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--runstatedir=/run
	
make
make install
```
However, I found the lib file is located at `/usr/lib/libmunge*`.
Besides,  I recompiled using.
```bash
./configure --prefix=/usr \
	--prefix=/usr \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--runstatedir=/run \
	--libdir=/usr/lib
```
It does not help.
Any suggestions?

**Comment by dun** [comment]
I suspect you just need to run `ldconfig`:
```
$ ldd /usr/sbin/mungekey | grep libmunge
        libmunge.so.2 => not found

$ sudo ldconfig

$ ldd /usr/sbin/mungekey | grep libmunge
        libmunge.so.2 => /lib/libmunge.so.2 (0x00007f2b4ce92000)
```

I'm guessing you're running 64-bit, in which case, if you had specified `--libdir=/usr/lib64` then you wouldn't have needed to run `ldconfig` afterwards:
```
$ sudo make install

$ ldd /usr/sbin/mungekey | grep libmunge
        libmunge.so.2 => /usr/lib64/libmunge.so.2 (0x00007f6b4b781000)
```

On CentOS 7, you could instead build & install RPMs as documented in the [Installation Guide](https://github.com/dun/munge/wiki/Installation-Guide#installing-from-rpm-on-centosfedora). `rpmbuild` will set `libdir` appropriately for the system:
```
$ rpm --eval %{_libdir}
/usr/lib64
```

**Comment by conanyangqun** [comment]
@dun
Thanks! I will have a try. Indeed I use a 64bit Centos7.

**Comment by conanyangqun** [comment]
Yes, below code is ok.
```bash
./configure --prefix=/usr \
	--prefix=/usr \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--runstatedir=/run \
	--libdir=/usr/lib64
```
Everything is ok, except that I can not start the service using root. So I have to add another one.
