### ISSUE TITLE
munge.service systemd unit file missing dependency ?

### ISSUE THREAD

**Issue by th-hummel** [dun/munge#75]
Hello, I'm using munge-0.5.13 on CentOS Linux release 8.1.1911 x86_64.
The rpm package unit file states the 2 following ordering dependencies:
```
After=network.target
After=time-sync.target
```
The upstream file `src/etc/munge.systemd.service.in` as well

The `/usr/lib/tmpfiles.d/munge.conf`, provided by the package, is processed by the `systemd-tmpfiles-setup.service` unit which itselfs is ordered `After=local-fs.target`

I experienced that, if local-fs.target takes some time to be available, munge.service activation fails because `/var/run/munge` has not been created yet.

So my question is : Do you think it would make sense to add the `After=systemd-tmpfiles-setup.service` dependency to the munge.service unit ?

Thanks for your help

--
Thomas HUMMEL

**Comment by dun** [comment]
Hmm... I'm not sure. I've been unable to reproduce this with munge-0.5.13-1.el8.x86_64 on a CentOS 8.1.1911 vm. I tried adding a delay to `systemd-tmpfiles-setup.service` using `ExecStartPre=sleep 10`, but that didn't affect the ordering. Any suggestions on how I can reproduce this?

Looking at the output of `systemctl list-dependencies --after munge.service`, `systemd-tmpfiles-setup.service` is already ordered to run before `munge.service` due to a dependency on `sysinit.target`.

Adding `After=systemd-tmpfiles-setup.service` to `munge.service` would be fine, but I've replaced the `tmpfiles.d` config with `RuntimeDirectory` as of 0.5.14 so this dependency is not warranted going forward. Still, several distros (including CentOS) will be running 0.5.13 in their supported releases for a while yet, so I'd like to determine whether a fix is necessary for 0.5.13.

When using the original `munge.service`, do you see `systemd-tmpfiles-setup.service` in the output from `systemctl list-dependencies --after munge.service`?

Also, when you say `munge.service` activation fails, I presume `/usr/sbin/munged` is not exec'd and nothing is written to `munged.log`, correct?

**Comment by th-hummel** [comment]
Hello, thanks for your answer,

> I tried adding a delay to `systemd-tmpfiles-setup.service` using `ExecStartPre=sleep 10`, but that didn't affect the ordering.

It is expected as, as you said, systemd-tmpfiles-setup.service is an ordering dependency of munge.service.

> Any suggestions on how I can reproduce this?

Well, what I actually did is add a service called localsratch.service (which basically formats and mount a local ssd drive) with a Before=local-fs.target ordering dependency. So my guess it that it just raised the time it takes to reach local-fs.target. So I would suggest you add a service unit doing your sleep with the same Before=local-fs.target dependency ?

I don't know exacly what's happening but as munge and systemd-tmpfiles-setup don't have any ordering dependencies between them, they could race after local-fs.target, couldn't they ?

Note : I don't have RunTimeDirectory in my unit file (came like this with the CentOS package)
 
> Looking at the output of `systemctl list-dependencies --after munge.service`, `systemd-tmpfiles-setup.service` is already ordered to run before `munge.service` due to a dependency on `sysinit.target`.

Yes, I did miss that indeed thus my initial guess was wrong.

> Adding `After=systemd-tmpfiles-setup.service` to `munge.service` would be fine, but I've replaced the `tmpfiles.d` config with `RuntimeDirectory` as of 0.5.14 so this dependency is not warranted going forward. 

This kind solves our problem. Except that again the package does not seem to come with it.
Besides I think indeed that RuntimeDirectory is a better solution in the munge case as it makes it independant from another service.

> When using the original `munge.service`, do you see `systemd-tmpfiles-setup.service` in the output from `systemctl list-dependencies --after munge.service`?

Yes.
 
> Also, when you say `munge.service` activation fails, I presume `/usr/sbin/munged` is not exec'd and nothing is written to `munged.log`, correct?

Yes.
```
# journalctl -u munge
-- Logs begin at Mon 2020-05-04 14:18:15 CEST, end at Mon 2020-05-04 18:50:01 CEST. --
May 04 14:19:06 maestro-1000.maestro.pasteur.fr systemd[1]: Starting MUNGE authentication ser>
May 04 14:19:06 maestro-1000.maestro.pasteur.fr systemd[1]: munge.service: Control process ex>
May 04 14:19:06 maestro-1000.maestro.pasteur.fr systemd[1]: munge.service: Failed with result>
May 04 14:19:06 maestro-1000.maestro.pasteur.fr systemd[1]: Failed to start MUNGE authenticat>
May 04 18:06:01 maestro-1000 systemd[1]: Starting MUNGE authentication service...
May 04 18:06:01 maestro-1000 systemd[1]: munge.service: Control process exited, code=exited s>
May 04 18:06:01 maestro-1000 systemd[1]: munge.service: Failed with result 'exit-code'.
May 04 18:06:01 maestro-1000 systemd[1]: Failed to start MUNGE authentication service.
```

Note : I'm using a systemd drop-in file to use syslog (but that does not change the issue)
```
# cat /etc/systemd/system/munge.service.d/exec-args.conf 
# Ansible managed, please don't edit this file directly

[Service]
EnvironmentFile=/etc/sysconfig/munge
ExecStart=
ExecStart=/usr/sbin/munged $DAEMON_ARGS
```

Here's the original package originated unit file:
```
# systemctl cat munge.service
# /usr/lib/systemd/system/munge.service
[Unit]
Description=MUNGE authentication service
Documentation=man:munged(8)
After=network.target
After=time-sync.target

[Service]
Type=forking
ExecStart=/usr/sbin/munged
PIDFile=/var/run/munge/munged.pid
User=munge
Group=munge
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

Thanks for your help.

--
Thomas HUMMEL

**Comment by th-hummel** [comment]
Hello,

Sorry for the confusion. What happened is that I added a Before=local-fs.target to my localscratch.service which caused systemd-tmpfiles-setup.service job to be " deleted to break ordering cycle starting with <my service>". That's all.
The cycle was:
```
systemd-tmpfiles-setup.service
    local-fs.target
        localscratch.service

localscratch.service
    basic.target
        sysinit.target
            systemd-tmpfiles-setup.service
```

So no problem. Sorry for bothering you.

--
TH

**Comment by dun** [comment]
Fantastic! Thanks for following-up. I'm glad you were able to track down the root cause.
