### ISSUE TITLE
Munge won't start. CentOS 7.8

### ISSUE THREAD

**Issue by Fplanas92** [dun/munge#76]
Hello,

Recently we have purchased some new nodes which came with CentOS 7.8. I have been installing munge and slurm on them, and I find that munge is not working.

Errors that I get:
>> sudo -u slurm service munge start

```
Job for munge.service failed because the control process exited with error code. See "systemctl status munge.service" and "journalctl -xe" for details.
[FAILED]
```

And, in the journal:

```
May 28 19:19:10 roos24.organ.su.se sudo[36738]:     root : TTY=pts/0 ; PWD=/tmp ; USER=slurm ; COMMAND=/sbin/service munge start
May 28 19:19:10 roos24.organ.su.se sudo[36738]: pam_unix(sudo:session): session opened for user slurm by root(uid=0)
May 28 19:19:10 roos24.organ.su.se polkitd[1308]: Registered Authentication Agent for unix-process:36758:420397 (system bus name :1.60 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAg
May 28 19:19:15 roos24.organ.su.se polkitd[1308]: Operator of unix-process:36758:420397 successfully authenticated as unix-user:root to gain ONE-SHOT authorization for action org.freedesktop.systemd1.manage-units for system-bus-name::1.61 
May 28 19:19:15 roos24.organ.su.se systemd[1]: Starting MUNGE authentication service...
-- Subject: Unit munge.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit munge.service has begun starting up.
May 28 19:19:15 roos24.organ.su.se munged[36771]: munged: Error: Failed to check logfile "/var/log/munge/munged.log": Permission denied
May 28 19:19:15 roos24.organ.su.se systemd[1]: munge.service: control process exited, code=exited status=1
May 28 19:19:15 roos24.organ.su.se systemd[1]: Failed to start MUNGE authentication service.
-- Subject: Unit munge.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
```

The logfile has de adequate ownership (slurm).

Reading other similar issues, I have seen that to check the socket is something is often asked. So here it goes:

>> sudo -u slurm munge -n -S /var/run/munge/munge.socket.2
`munge: Error: Failed to access "/var/run/munge/munge.socket.2": No such file or directory`

The /var/run/munge folder is also owned by the slurm user.

Thinks I have tried to fix the problem, which have been suggested in this site:
- Uninstall and install munge from slurm: Nothing changed

I would appreciate some help. I know this might be a basic problem, but is driving me crazy.

Many thanks,
Ferran

**Comment by dun** [comment]
The MUNGE daemon (`munged`) should run as a dedicated non-privileged user (e.g., munge). It should not be started by slurm. The munge user should own the directories `/etc/munge`, `/var/lib/munge`, `/var/log/munge`, and `/run/munge`. Permissions & ownership are discussed in the [Installation Guide](https://github.com/dun/munge/wiki/Installation-Guide#securing-the-installation).

CentOS 7.8.2003 has munge-0.5.11 which can be installed via:
```
$ sudo yum install munge
$ sudo /usr/sbin/create-munge-key
$ sudo systemctl start munge.service
$ sudo systemctl enable munge.service
```
The rpm will create the munge user, and its systemd service file will run `munged` under that user.

If you want to run the latest release (0.5.14), the directions for building the rpm are also in the [Installation Guide](https://github.com/dun/munge/wiki/Installation-Guide#installing-from-rpm-on-centosfedora).

**Comment by Fplanas92** [comment]
Hi Chris,

Thanks for your answer.
I do have CentOS 7.8.2003.
However, if I run 'sudo yum install munge' I get the following:

Loaded plugins: fastestmirror

Loading mirror speeds from cached hostfile

 * base: mirrors.glesys.net

 * extras: mirrors.dotsrc.org

 * updates: mirrors.glesys.net

No package *munge* available.

**Comment by dun** [comment]
It's in the EPEL repo:
```
$ yum info munge
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirror.ndchost.com
 * epel: mirrors.sonic.net
 * extras: mirrors.sonic.net
 * updates: mirror.keystealth.org
Available Packages
Name        : munge
Arch        : x86_64
Version     : 0.5.11
Release     : 3.el7
Size        : 95 k
Repo        : epel/x86_64
...
```
This is the repo list I have:
```
$ yum repolist
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirror.ndchost.com
 * epel: sjc.edge.kernel.org
 * extras: repos.lax.layerhost.com
 * updates: mirror.keystealth.org
repo id               repo name                                           status
base/7/x86_64         CentOS-7 - Base                                     10070
epel/x86_64           Extra Packages for Enterprise Linux 7 - x86_64      13300
extras/7/x86_64       CentOS-7 - Extras                                     397
updates/7/x86_64      CentOS-7 - Updates                                    671
repolist: 24438

$ yum repoinfo epel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirror.ndchost.com
 * epel: sjc.edge.kernel.org
 * extras: repos.lax.layerhost.com
 * updates: mirror.keystealth.org
Repo-id      : epel/x86_64
Repo-name    : Extra Packages for Enterprise Linux 7 - x86_64
Repo-status  : enabled
Repo-revision: 1590713483
Repo-updated : Thu May 28 17:53:04 2020
Repo-pkgs    : 13300
Repo-size    : 15 G
Repo-metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=x86_64&infra=stock&content=centos
  Updated    : Thu May 28 17:53:04 2020
Repo-baseurl : https://sjc.edge.kernel.org/fedora-buffet/epel/7/x86_64/ (53
             : more)
Repo-expire  : 21600 second(s) (last: Fri May 29 08:23:03 2020)
  Filter     : read-only:present
Repo-filename: /etc/yum.repos.d/epel.repo

repolist: 13300
```

More info on the Extra Packages for Enterprise Linux (EPEL) can be found here:
https://fedoraproject.org/wiki/EPEL
