### ISSUE TITLE
munge-0.5.14 does not install tmpfiles.d

### ISSUE THREAD

**Issue by TimoRoth** [dun/munge#78]
Ever since https://github.com/dun/munge/commit/9abebcd6ff62f56039e0ec299b16ad54db0ee4c4 the tmpfiles.d file is no longer installed, resulting in issues on systems with /run in a tmpfs on every boot.

**Comment by dun** [comment]
The tmpfiles.d config was replaced with the systemd unit directives [`RuntimeDirectory`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectory=) and [`RuntimeDirectoryMode`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectoryMode=) in 3eed37e3ca73c14b679394df7be151d27566b0fe.

These directives were added in systemd 211 (released on 2014-03-11). I'm guessing you must be running an older version of systemd that doesn't support these unit directives.

**Comment by TimoRoth** [comment]
Oh, it was an issue with /var/run vs. /run, where they were not symlinked to the same dir anymore instead. And munge was trying to use /var/run instead.
Will rebuild munge with the currect runtime dir set.

**Comment by dun** [comment]
Thanks for following up. I'm glad you got it figured out.
