### ISSUE TITLE
Not able to start munge 0.5.14 on CentOS7 and AmazonLinux2

### ISSUE THREAD

**Issue by lukeseawalker** [dun/munge#82]
I'm getting an error while starting munge 0.5.14 on CentOS7 and AmazonLinux2
I had no issue with version 0.5.13, using same setup. Can you please help?

output of `systemctl status munge`
```
munge.service - MUNGE authentication service
   Loaded: loaded (/usr/lib/systemd/system/munge.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2020-10-27 09:33:12 UTC; 2min 54s ago
     Docs: man:munged(8)
  Process: 3481 ExecStart=/usr/sbin/munged $OPTIONS (code=exited, status=233/RUNTIME_DIRECTORY)

Oct 27 09:33:12 ip-172-31-0-180 systemd[1]: Starting MUNGE authentication service...
Oct 27 09:33:12 ip-172-31-0-180 systemd[1]: munge.service: control process exited, code=exited status=233
Oct 27 09:33:12 ip-172-31-0-180 systemd[1]: Failed to start MUNGE authentication service.
Oct 27 09:33:12 ip-172-31-0-180 systemd[1]: Unit munge.service entered failed state.
Oct 27 09:33:12 ip-172-31-0-180 systemd[1]: munge.service failed.
```

output of `journalctl -xe`
```
-- Subject: Unit munge.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit munge.service has begun starting up.
Oct 27 09:33:12 ip-172-31-0-180 systemd[3481]: Failed at step RUNTIME_DIRECTORY spawning /usr/sbin/munged: File exists
-- Subject: Process /usr/sbin/munged could not be executed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- The process /usr/sbin/munged could not be executed and failed.
--
-- The error number returned by this process is 17.
Oct 27 09:33:12 ip-172-31-0-180 systemd[1]: munge.service: control process exited, code=exited status=233
Oct 27 09:33:12 ip-172-31-0-180 systemd[1]: Failed to start MUNGE authentication service.
-- Subject: Unit munge.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit munge.service has failed.
--
-- The result is failed.
Oct 27 09:33:12 ip-172-31-0-180 systemd[1]: Unit munge.service entered failed state.
Oct 27 09:33:12 ip-172-31-0-180 systemd[1]: munge.service failed.
```

I'm installing from sources with 
```
./bootstrap
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=/usr/lib64
CORES=$(grep processor /proc/cpuinfo | wc -l)
make -j $CORES
make install
```

ouput of `ls -la /var/log/munge/`
```
total 4
drwx------   2 munge root    6 Oct 27 09:29 .
drwxr-xr-x. 22 root  root 4096 Oct 27 09:29 ..
```

ouput of `ls -la /etc/munge/`
```
total 20
drwx------    2 munge root    23 Oct 27 09:32 .
drwxr-xr-x. 147 root  root 12288 Oct 27 09:32 ..
-rw-------    1 munge root    82 Oct 27 09:32 munge.key
```

output of `cat /usr/lib/systemd/system/munge.service`
```
[Unit]
Description=MUNGE authentication service
Documentation=man:munged(8)
After=network.target
After=time-sync.target

[Service]
Type=forking
EnvironmentFile=-/etc/sysconfig/munge
ExecStart=/usr/sbin/munged $OPTIONS
PIDFile=/var/run/munge/munged.pid
RuntimeDirectory=munge
RuntimeDirectoryMode=0755
User=munge
Group=munge
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

output of ls -la `/usr/sbin/munge*`
```
-rwxr-xr-x 1 root root 484416 Oct 27 09:29 /usr/sbin/munged
-rwxr-xr-x 1 root root 156432 Oct 27 09:29 /usr/sbin/mungekey
```

Thanks,
L

**Comment by dun** [comment]
0.5.14 switched to using `RuntimeDirectory` and `RuntimeDirectoryMode` in the systemd service unit configuration file.

Based on the `journalctl -xe` output above, it appears that systemd is entering the failed state for the service when attempting to create the `RuntimeDirectory` `/run/munge` before starting `/usr/sbin/munged`:
```
systemd[3481]: Failed at step RUNTIME_DIRECTORY spawning /usr/sbin/munged: File exists
```

Does `/run/munge` already exist?

If so, what are its permissions (i.e., `ls -ld /run/munge`)?

And if you remove it, are you then able to start the service?

**Comment by lukeseawalker** [comment]
Thanks a lot, I think I'm closer to the solution.
So after the `make install` I had the `/run/munge` created and owned by root (not sure why yet).
Changing both ownership and groupship of the `/run/munge` to be of the user `munge` or even deleting `/run/munge` before starting the service is letting the service to start successful.

**Comment by dun** [comment]
OK, that makes sense. Lennart Poettering [writes](https://lists.freedesktop.org/archives/systemd-devel/2015-August/033828.html):

> So, you'll get this `EEXIST` error only if there's already something at the place of the runtime dir that is either:
> 
> a) not a directory
> 
> or
> 
> b) a directory, but not owned by the user and group set for the service
> 
> or
> 
> c) a directory, but with a more loose access mode than specified in `RuntimeDirectoryMode=`.
> 
> systemd is completely fine with the directory pre-existing, as long as it really is a directory, is owned by the right user and group and has an access mode that is at least as strict as the configured one.

As of 0.5.14, the `munge.service` config specifies this directory should be owned by user `munge` with `0755` permissions.

If you run `make install` as root, it creates the directory `$(runstatedir)/munge` as `root`; and it can't necessarily `chown` it to user `munge` since that user might not exist. This is the cause of your problem since the directory ownership doesn't match the `munge.service` config.

If you reboot, `/run` is cleared since it's a `tmpfs` filesystem. If you install the rpm, `/run/munge` isn't created during package installation -- it's marked with the `%ghost` attribute in `munge.spec`.

Hmm... I'm thinking maybe `/run/munge` shouldn't be created during `make install` on systemd-based installations. But this also needs to work on non-systemd installations in which case that directory needs to be created. I need to do some more testing to figure out the best course of action here.

**Comment by lukeseawalker** [comment]
I have solved setting `munge` groupship to "/var/log/munge", "/etc/munge" and "/var/run/munge", without touching the ownership of the "/run/munge" (so I suspect it's still of root after the make install).
Before I was setting only the `munge` owner to those dirs and not the groupship.

Hope this helps.
This can be closed from my side, thanks a lot.
