### ISSUE TITLE
Installation on Cent OS 8

### ISSUE THREAD

**Issue by bkmgit** [dun/munge#90]
Related to #80 there are also packages for Cent OS 8 
* http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/munge-0.5.13-1.el8.x86_64.rpm
* http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/munge-libs-0.5.13-1.el8.i686.rpm
* http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/munge-libs-0.5.13-1.el8.x86_64.rpm

Installing from source requires the following procedure
```
     sudo dnf -y update
     sudo dnf -y install epel-release
     sudo dnf config-manager --set-enabled PowerTools
     sudo dnf install -y python3-devel
     sudo dnf group install "Development Tools"
     wget https://github.com/dun.gpg
     wget https://github.com/dun/munge/archive/munge-0.5.14.tar.gz
     wget https://github.com/dun/munge/releases/download/munge-0.5.14/munge-0.5.14.tar.xz
     wget https://github.com/dun/munge/releases/download/munge-0.5.14/munge-0.5.14.tar.xz.asc
     wget https://github.com/dun/munge/releases/download/munge-0.5.14/munge-0.5.14.tar.xz.sha512
     sudo dnf -y install zlib-devel openssl-devel bzip2-devel
     rpmbuild -tb munge-0.5.14.tar.xz
    sudo dnf -y install rpmbuild/RPMS/x86_64/munge-libs-0.5.14-1.el8.x86_64.rpm rpmbuild/RPMS/x86_64/munge-0.5.14-1.el8.x86_64.rpm rpmbuild/RPMS/x86_64/munge-devel-0.5.14-1.el8.x86_64.rpm
     sudo dnf install selinux-policy-devel 
     sudo -u munge /usr/sbin/mungekey --verbose
     sudo systemctl enable munge
     sudo systemctl start munge
```

Note that setting up the munge key is important, otherwise the service will not start. It may be helpful for the rpm package to generate a key or issue a suggestion to generate the key.

**Comment by dun** [comment]
@bkmgit Thanks for the procedure!

Is `selinux-policy-devel ` needed? I haven't gotten around to adding SELinux support yet.

Also, I don't do anything with python, so what is requiring `python3-devel`?

In the `munge.spec` I distribute, I echo a [message](https://github.com/dun/munge/blob/cdfdf73ca62182e775ef210304cbe791a7c43f4a/munge.spec#L106) in `%post` that `mungekey` needs to be run to create a key. I'm not convinced it makes sense to always generate a key if one is not present, since you really need to generate a key on only one host and distribute it to other hosts with which you want to authenticate.

But, I admit, the following error message (while technically accurate) could be phrased better:
```
Error: Failed to check keyfile "/etc/munge/munge.key": No such file or directory
```
I should probably note there that they might want to run `mungekey` to create a key.

**Comment by truatpasteurdotfr** [comment]
Hi, 

you can retrieve the spec file and upgrade the version and rebuild from there:
```
git clone https://git.centos.org/rpms/munge.git
cd munge && git checkout c8
```
https://git.centos.org/rpms/munge/blob/c8/f/SPECS

**Comment by dun** [comment]
@truatpasteurdotfr The current spec file works on CentOS 7/8 and recent Fedora releases. The latest spec distributed by CentOS is for 0.5.13.

**Comment by adutoi** [comment]
Struggling/sophomore/reluctant sys-admin here:

I can see that I have munge installed on my system

```
# sudo dnf list all | grep munge
munge.x86_64                                                                             0.5.13-13.el9                        @appstream
munge-libs.x86_64                                                                        0.5.13-13.el9                        @appstream
munge-libs.i686                                                                          0.5.13-13.el9                        appstream 
```

But mungekey appears to not have been part of the package install.
```
no mungekey in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
```

Is my only choice to adapt the procedure above to 2023 and compile from source? . . . that's usually the beginning of a bad afternoon . . .

Thanks for any pointers!

**Comment by dun** [comment]
@adutoi: No worries. You don't need to compile anything to remedy this.

`mungekey` was added in 0.5.14. CentOS 8 has 0.5.13. You can verify the installed version with either `munge --version` or `rpm -q munge`.

On CentOS 8, create a key with `sudo /usr/sbin/create-munge-key`.

Then you'll need to securely copy that key to the other hosts in the munge realm and start `munged` on each host (`sudo systemctl start munge.service`).

**Comment by adutoi** [comment]
Eeeexxxellent!  That's all I needed.  Worked.  Thank you!

**Comment by dun** [comment]
You're welcome.
