### ISSUE TITLE
help me please with munge

### ISSUE THREAD

**Issue by Escanor2099** [dun/munge#92]
i am usin centos 7 and i installed munge but when i use " sudo systemctl start munge " the output is the next:

Job for munge.service failed because the control process exited with error code. See "systemctl status munge.service" and "journalctl -xe" for details

The output of "systemctl status munge.service" is:

[ayv@localhost ~]$ systemctl status munge.service
● munge.service - MUNGE authentication service
   Loaded: loaded (/usr/local/lib/systemd/system/munge.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since mar 2020-12-15 12:54:34 CST; 13s ago
     Docs: man:munged(8)
  Process: 27039 ExecStart=/usr/local/sbin/munged (code=exited, status=217/USER)

dic 15 12:54:34 localhost.localdomain systemd[1]: Starting MUNGE authentication service...
dic 15 12:54:34 localhost.localdomain systemd[1]: munge.service: control process exited, code=exited status=217
dic 15 12:54:34 localhost.localdomain systemd[1]: Failed to start MUNGE authentication service.
dic 15 12:54:34 localhost.localdomain systemd[1]: Unit munge.service entered failed state.
dic 15 12:54:34 localhost.localdomain systemd[1]: munge.service failed.

when i use "journalctl -xe" 

[ayv@localhost ~]$ journalctl -xe
-- 
-- Unit munge.service has begun starting up.
dic 15 13:34:34 localhost.localdomain systemd[28155]: Failed at step USER spawning /usr/local/sbin/munged: No such process
-- Subject: Process /usr/local/sbin/munged could not be executed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The process /usr/local/sbin/munged could not be executed and failed.
-- 
-- The error number returned by this process is 3.
dic 15 13:34:34 localhost.localdomain systemd[1]: munge.service: control process exited, code=exited status=217
dic 15 13:34:34 localhost.localdomain systemd[1]: Failed to start MUNGE authentication service.
-- Subject: Unit munge.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit munge.service has failed.
-- 
-- The result is failed.
dic 15 13:34:34 localhost.localdomain systemd[1]: Unit munge.service entered failed state.
dic 15 13:34:34 localhost.localdomain systemd[1]: munge.service failed.
dic 15 13:34:34 localhost.localdomain sudo[28141]: pam_unix(sudo:session): session closed for user root
dic 15 13:34:34 localhost.localdomain polkitd[735]: Unregistered Authentication Agent for unix-process:28149:190086631 (system bus name :1.8395, objec
dic 15 13:34:35 localhost.localdomain sshd[28147]: Invalid user fernie from 94.237.100.214 port 55116
dic 15 13:34:35 localhost.localdomain sshd[28147]: input_userauth_request: invalid user fernie [preauth]
dic 15 13:34:35 localhost.localdomain sshd[28147]: pam_unix(sshd:auth): check pass; user unknown
dic 15 13:34:35 localhost.localdomain sshd[28147]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=94-237-100-
dic 15 13:34:35 localhost.localdomain sshd[28145]: Received disconnect from 206.189.122.115 port 50832:11: Bye Bye [preauth]
dic 15 13:34:35 localhost.localdomain sshd[28145]: Disconnected from 206.189.122.115 port 50832 [preauth]
dic 15 13:34:37 localhost.localdomain sshd[28147]: Failed password for invalid user fernie from 94.237.100.214 port 55116 ssh2
dic 15 13:34:37 localhost.localdomain sshd[28147]: Received disconnect from 94.237.100.214 port 55116:11: Bye Bye [preauth]
dic 15 13:34:37 localhost.localdomain sshd[28147]: Disconnected from 94.237.100.214 port 55116 [preauth]
dic 15 13:34:42 localhost.localdomain sshd[28163]: Address 104.131.46.166 maps to tcwebadmin.com, but this does not map back to the address - POSSIBLE
dic 15 13:34:42 localhost.localdomain sshd[28163]: Invalid user csserver from 104.131.46.166 port 55672
dic 15 13:34:42 localhost.localdomain sshd[28163]: input_userauth_request: invalid user csserver [preauth]
dic 15 13:34:42 localhost.localdomain sshd[28163]: pam_unix(sshd:auth): check pass; user unknown
dic 15 13:34:42 localhost.localdomain sshd[28163]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=104.131.46.
dic 15 13:34:44 localhost.localdomain sshd[28163]: Failed password for invalid user csserver from 104.131.46.166 port 55672 ssh2
dic 15 13:34:44 localhost.localdomain sshd[28163]: Received disconnect from 104.131.46.166 port 55672:11: Bye Bye [preauth]
dic 15 13:34:44 localhost.localdomain sshd[28163]: Disconnected from 104.131.46.166 port 55672 [preauth]
dic 15 13:34:47 localhost.localdomain sshd[28161]: Invalid user sybsrj from 122.146.196.217 port 41349
dic 15 13:34:47 localhost.localdomain sshd[28161]: input_userauth_request: invalid user sybsrj [preauth]
dic 15 13:34:47 localhost.localdomain sshd[28161]: pam_unix(sshd:auth): check pass; user unknown
dic 15 13:34:47 localhost.localdomain sshd[28161]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=122.146.196

Sombody help me please, 
i tryed looking for this issue but i can't founded nothing!

**Comment by dun** [comment]
Did you create a key first?

What is the output from `journalctl _UID=$(id -u munge)`?

**Comment by Escanor2099** [comment]
i'm sorry, have i to substitute some value on the **journalctl _UID=$(id -u munge)** ?

**Comment by dun** [comment]
Nope, just type it exactly as it appears.

The `$(...)` construct performs shell command substitution.  In this case, the output from `id -u munge` will be assigned to the variable `_UID` which has special significance to `journalctl`.

**Comment by dun** [comment]
Also, what version are you running?  Send the output from `munged --version`.

**Comment by Escanor2099** [comment]
thank you!
The output from journalctl _UID=$(id -u munge) is:

[ayv@localhost ~]$ journalctl _UID=$(id -u munge)
id: munge: no existe ese usuario
-- No entries --

and 

[ayv@localhost ~]$ munged --version
munge-0.5.13 (2017-09-26)

I noticed the most recent version is munge-0.5.14,
I thought I installed the latter, but it appears that I have version 0.5.13

**Comment by dun** [comment]
OK, so the `munge` user does not exist, and you don't appear to be running the CentOS 7 rpm from the `epel` repo.

How did you install munge? What are the steps you've done so far?

**Comment by Escanor2099** [comment]
oh, i utiliced the next instructions 

tar xJf munge-0.5.14.tar.xz \
  && cd munge-0.5.14          \
  && ./configure              \
     --prefix=/usr            \
     --sysconfdir=/etc        \
     --localstatedir=/var     \
     --runstatedir=/run       \
  && make                     \
  && make check               \
  && sudo make install

**Comment by dun** [comment]
Looking at your output above from `systemctl status munge.service`, it looks like munge is installed under `/usr/local` and not `/usr`. But that's fine, too. You can check the default key file location with:
```
$ munged --help | grep key-file
  --key-file=PATH          Specify secret key file [/etc/munge/munge.key]
```

I'm guessing you're using `/usr/local/etc/munge/munge.key`, but if not, substitute the appropriate location in the commands below.

I think you need to create a `munge` user and group since the `/usr/local/lib/systemd/system/munge.service` systemd service config will try to run `munged` as the `munge` user.  This account would normally be created when installing the munge rpm, but you can create it manually by:
```
$ sudo groupadd -r munge
$ sudo useradd -c "MUNGE authentication service" -d /usr/local/etc/munge -g munge -s /sbin/nologin -r munge
```

Afterwards, you can check to see if the `munge` user and group have been created by entering the following command:
```
$ id munge
```

If you haven't already done so, you'll need to create a key. If you're running 0.5.13, you'll need to do this manually:
```
$ sudo -i
# mkdir -p /usr/local/etc/munge
# chown munge:munge /usr/local/etc/munge
# chmod 0700 /usr/local/etc/munge
# dd if=/dev/urandom bs=1 count=1024 >/usr/local/etc/munge/munge.key
# chown munge:munge /usr/local/etc/munge/munge.key
# chmod 0400 /usr/local/etc/munge/munge.key
```

After this, you should be able to start `munged`:
```
$ sudo systemctl start munge
```

If not, send the output from `journalctl _UID=$(id -u munge)`. That should have the error message.

**Comment by Escanor2099** [comment]
Ohh I am very grateful with you. I am gonna do it and I'll be here for comment the output. again thank you.

**Comment by Escanor2099** [comment]
I am sorry for the delay of the answer, but I was a little busy and I barely left.

very well, i created the munge user and group. the output of id munge was:

[root@localhost ~]# id munge
uid=985(munge) gid=979(munge) grupos=979(munge)

i did the steps

$ sudo -i
# mkdir -p /usr/local/etc/munge
# chown munge:munge /usr/local/etc/munge
# chmod 0700 /usr/local/etc/munge
# dd if=/dev/urandom bs=1 count=1024 >/usr/local/etc/munge/munge.key
# chown munge:munge /usr/local/etc/munge/munge.key
# chmod 0400 /usr/local/etc/munge/munge.key

and finally i try to start the munged service but i can't, this is the output:

[ayv@localhost ~]$ sudo systemctl start munge
[sudo] password for ayv: 
Job for munge.service failed because the control process exited with error code. See "systemctl status munge.service" and "journalctl -xe" for details.

The output of journalctl _UID=$(id -u munge) is:

[ayv@localhost ~]$ journalctl _UID=$(id -u munge)
-- Logs begin at mar 2020-12-15 01:56:19 CST, end at mié 2020-12-16 23:25:08 CST. --
dic 16 23:06:43 localhost.localdomain munged[28367]: munged: Error: Failed to check logfile "/usr/local/var/log/munge/munged.log": Permission denied

again i am very grateful to you for helping me in this situation.

**Comment by dun** [comment]
Looks like the `/usr/local/var/log/munge` directory is owned by `root`.  The `lib/munge` directory will presumably have the same problem.  Directory ownership & permissions are documented in the [Installation Guide](https://github.com/dun/munge/wiki/Installation-Guide#securing-the-installation).  To fix:
```
sudo chown -R munge:munge /usr/local/var/log/munge
sudo chown -R munge:munge /usr/local/var/lib/munge
```

**Comment by Escanor2099** [comment]
I run the commands and then I run "sudo systemctl start munge" but I obtained the next output with "journalctl _UID=$(id -u munge)"

-- Logs begin at mar 2020-12-15 01:56:19 CST, end at jue 2020-12-17 00:44:56 CST. --                                                                                                                                              dic 16 23:06:43 localhost.localdomain munged[28367]: munged: Error: Failed to check logfile "/usr/local/var/log/munge/munged.log": Permission denied
dic 16 23:23:52 localhost.localdomain munged[28868]: munged: Error: Failed to check logfile "/usr/local/var/log/munge/munged.log": Permission denied
dic 17 00:19:49 localhost.localdomain munged[30360]: munged: Error: Failed to create "/usr/local/var/run/munge/munge.socket.2.lock": Permission denied
dic 17 00:30:21 localhost.localdomain munged[30985]: munged: Error: Failed to create "/usr/local/var/run/munge/munge.socket.2.lock": Permission denied
dic 17 00:38:50 localhost.localdomain munged[31594]: munged: Error: Failed to create "/usr/local/var/run/munge/munge.socket.2.lock": Permission denied

**Comment by dun** [comment]
Same problem, same fix. `/usr/local/var/run/munge` is owned by `root`, so:
```
$ sudo chown -R munge:munge /usr/local/var/run/munge
```

**Comment by Escanor2099** [comment]
Thanks my friend, you have helped me a lot to advance in my project, and finally I was able to start the munge service.
Take care. 👍

**Comment by dun** [comment]
Glad to hear you got it up and running.
