### ISSUE TITLE
Munge starting before DNS is ready

### ISSUE THREAD

**Issue by plysdyret** [dun/munge#93]
Hi

After a reboot:

```
# bigger10/root ~ 
# uptime
 09:48:38 up 0 min,  1 user,  load average: 1.79, 0.59, 0.20
# bigger10/root ~ 
# systemctl status munge
● munge.service - MUNGE authentication service
   Loaded: loaded (/usr/lib/systemd/system/munge.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2020-12-28 09:48:01 CET; 43s ago
     Docs: man:munged(8)
 Main PID: 1682 (munged)
    Tasks: 4 (limit: 1648064)
   Memory: 2.2M
   CGroup: /system.slice/munge.service
           └─1682 /usr/sbin/munged

Dec 28 09:48:01 bigger10.drcmr systemd[1]: Starting MUNGE authentication service...
Dec 28 09:48:01 bigger10.drcmr munged[1669]: munged: Warning: Failed to lookup origin "bigger10.drcmr": Resource temporarily unavailable
Dec 28 09:48:01 bigger10.drcmr munged[1669]: munged: Warning: Continuing with origin set to null address
Dec 28 09:48:01 bigger10.drcmr systemd[1]: Started MUNGE authentication service.
# bigger10/root ~ 
```

Leading to errors like these in SLURM:

```
[2020-12-16T09:02:33.737] error: slurm_auth_get_host: Lookup failed for 0.0.0.0
[2020-12-16T09:02:53.429] error: slurm_auth_get_host: Lookup failed for 127.0.0.2
```

Munged starts before DNS is available, so we had to restart munged manually after reboots. A permanent fix could be to change "After=network.target" to "After=network-online.target" in munge.service. Perhaps there is a better solution?

Thanks,

Torkil

**Comment by dun** [comment]
Yes, I think you're correct (see [link](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/)). Adding `
Wants=network-online.target` and `After=network-online.target` is probably the best solution. I think the main downside is this could delay system boot. Can you try modifying your `munge.service` unit to verify this solves the problem?

If running 0.5.14, another option would be to start `munged` with `--origin=1.2.3.4` to explicitly specify the IP address so hostname resolution is not required. On a related note, if the origin address is being set to something like 127.0.0.2, you may still need to use `--origin=` to specify an IP address or network interface name, or modify `/etc/hosts` accordingly.

**Comment by plysdyret** [comment]
> Yes, I think you're correct (see [link](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/)). Adding ` Wants=network-online.target` and `After=network-online.target` is probably the best solution. I think the main downside is this could delay system boot. Can you try modifying your `munge.service` unit to verify this solves the problem?

This solves it for us, yes.

> If running 0.5.14, another option would be to start `munged` with `--origin=1.2.3.4` to explicitly specify the IP address so hostname resolution is not required. On a related note, if the origin address is being automatically set to something like 127.0.0.2 above, you may still need to use `--origin=` to specify an IP address or network interface name, or modify `/etc/hosts` accordingly.

The changes to the service file is a better solution for us, but thanks for the clarification.

**Comment by dun** [comment]
Thanks for the update. I'll make the change to the service file for 0.5.15. I'm hoping to get that out in the next month or so.
