### ISSUE TITLE
where is the configure file in both this release and in the master stream?

### ISSUE THREAD

**Issue by allenzhao64** [dun/munge#95]
[root@dinero munge-munge-0.5.14]# ls
AUTHORS       COPYING.LESSER   HISTORY  Makefile.am  QUICKSTART       src
bootstrap     DISCLAIMER.LLNS  INSTALL  Make-inc.mk  README           t
build-aux     DISCLAIMER.UC    JARGON   munge.spec   README.AIX       THANKS
configure.ac  doc              KEYS     NEWS         README.md
COPYING       extra            m4       PLATFORMS    README.MULTILIB
[root@dinero munge-munge-0.5.14]# find . -name configure -print
[root@dinero munge-munge-0.5.14]#

I could not find any trace of it in the  extracted files.

**Comment by dun** [comment]
Autotools-generated files (including `configure`) were removed from version control in 46dd77ba9bfc2d9f7ce6933e79769eeddae9315c.

The `configure` script is included in the official release tarball (e.g., [munge-0.5.14.tar.xz](https://github.com/dun/munge/releases/download/munge-0.5.14/munge-0.5.14.tar.xz)).

But if you're building from a `git clone` or `git archive` (e.g., the GitHub-generated [source code asset](https://github.com/dun/munge/archive/munge-0.5.14.tar.gz) link), then you'll need to install the appropriate dependencies (e.g., `autoconf`, `automake`, `libtool`) and run `./bootstrap`. That will generate `configure`.

**Comment by allenzhao64** [comment]
thanks for pointer. it works.
