### ISSUE TITLE
Starting Munge Daemon on Mac OS Catalina

### ISSUE THREAD

**Issue by carlos-pereyra** [dun/munge#97]
I recognize this may be a bit of a pipe dream, but I was wondering if there is a way to start Munge on Mac OS X Catalina (the goal is to eventually enable slurm)?

I am able to make and install, and have generated a munge key within my etc directory. But since Mac OS does not work with systemctl to enable munge, I have tried to enable munge with launchctl to no avail. ```launchctl enable munge``` does not seem to work - the error is below.

```
Unrecognized target specifier. <service-target> takes a form of <domain-target>/<service-id>.
Please refer to `man launchctl` for explanation of the <domain-target> specifiers.
Usage: launchctl enable <service-target>
```

I am bit confused since I have munge in my path (```which munge ``` yields path to executable), but I guess I expected the service-target to be the executable but I am wrong. I am unfamiliar with launchctl so I was wondering If I could have any help providing the proper service-target? Thanks again, I appreciate any suggestion or help as I understand you may be busy.

**Comment by dun** [comment]
I don't have access to a Mac OS X system for testing. But I think you just need to create a launchd property list (.plist) file. Apple's [developer documentation](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html) recommends the manual pages for `launchd` and `launchd.plist` as the two best sources for information about `launchd`.

**Comment by dun** [comment]
The munge socket (`munge.socket.2`) only exists while `munged` is running.

Good job on the property list!

**Comment by outpaddling** [comment]
> I see thanks.
> 
> Using the link you provided I was able to create a simple property list and add it to my /Library/LaunchAgents/
> 
> By loading the plist, `launchctl load /Library/LaunchAgents/com.munge.plist`, this got munge is up and running. You can check with `launchctl list | grep munge` and as long as there's no negative number in the status I suppose its good.
> 
> Also side note I had some trouble verifying my installation. Running `munge -n` gave me the classic socket error at first. For whatever reason I had to manually execute `munged` which seems to have generated the required `munge.socket.2` files then I could verify the installation.
> 
> -Thanks again

Would you please share your .plist file?  This could be useful to other Mac users.  Thank you...

**Comment by outpaddling** [comment]
FYI, the following is a minimal .plist that works for me, using the default prefix for the pkgsrc package manager.
https://launchd.info/ has a good explanation of how launchd works and how to write a .plist.
Note that the launchd.plist man page states that programs run by launchd should not call daemon() or otherwise fork.  I suspect that munge does fork if run without --foreground, but it works fine on my Mac M1 with no arguments.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>org.pkgsrc.munge</string>
        <key>Program</key>
        <string>/opt/pkg/sbin/munged</string>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <true/>
    </dict>
</plist>
```

**Comment by dun** [comment]
Thanks, @outpaddling! :star:
