### ISSUE TITLE
munged: Error: PRNG seed dir is insecure: group-writable permissions without sticky bit set on "/"

### ISSUE THREAD

**Issue by handrake0724** [dun/munge#99]
# What steps will reproduce the problem?

Start munged with systemctl start munge on CentOS 7.6 

# What is the expected output? What do you see instead?

munged should start but it fails and exits:
```
-- Unit munge.service has begun starting up.
Apr 14 17:35:13 hnode0 munged[31406]: munged: Error: PRNG seed dir is insecure: group-writable permissions without sticky bit set on "/"
Apr 14 17:35:13 hnode0 systemd[1]: munge.service: control process exited, code=exited status=1
Apr 14 17:35:13 hnode0 systemd[1]: Failed to start MUNGE authentication service.
-- Subject: Unit munge.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
```
# What version of the software are you using? On what operating system?

munge-0.5.14 on CentOS 7.6

**Comment by dun** [comment]
The error is:
```
munged: Error: PRNG seed dir is insecure: group-writable permissions without sticky bit set on "/"
```

From the [Installation Guide](https://github.com/dun/munge/wiki/Installation-Guide#securing-the-installation):
> These directories must be owned by the same user as the running daemon process. They cannot allow write permissions for group unless the sticky bit is set or the directory is owned by the trusted group (see munged for details on the --trusted-group option), and they cannot allow write permissions for other unless the sticky bit is set. In addition, all of their parent directories in the path on up to the root directory must be owned by either root or the same user as the daemon process. They cannot allow write permissions for group unless the sticky bit is set or the directory is owned by the trusted group, and they cannot allow write permissions for other unless the sticky bit is set.

When `munged` was checking directory permissions and ownership, it found group-write permissions set on the `/` directory. This is a security issue so `munged` immediately exits with an error. You can either fix the problem (`sudo chmod g-w /`) or run `munged` with the `--force` command-line option which overrides warnings for an existing local domain socket, a lack of entropy for the PRNG, and insecure file/directory permissions; use with caution as overriding these warnings can affect security.

**Comment by handrake0724** [comment]
Thank you so much. I asked admin for changing the permission. It works.

**Comment by dun** [comment]
You're welcome.
